/** 从当前游戏配置导出的本地英雄基础数值。 */
module.exports = [
  {
    "id": 1101,
    "name": "冰女",
    "pic": 1,
    "icon": 101,
    "cost": 1,
    "color": 1,
    "hp": 550,
    "attack": 50,
    "armor": 10,
    "race": "0",
    "profession": "2"
  },
  {
    "id": 1102,
    "name": "斧王",
    "pic": 2,
    "icon": 102,
    "cost": 1,
    "color": 1,
    "hp": 700,
    "attack": 60,
    "armor": 20,
    "race": "1",
    "profession": "0"
  },
  {
    "id": 1103,
    "name": "小黑",
    "pic": 3,
    "icon": 103,
    "cost": 1,
    "color": 1,
    "hp": 600,
    "attack": 65,
    "armor": 15,
    "race": "2",
    "profession": "1"
  },
  {
    "id": 1104,
    "name": "敌法",
    "pic": 4,
    "icon": 111,
    "cost": 1,
    "color": 1,
    "hp": 600,
    "attack": 66,
    "armor": 15,
    "race": "3",
    "profession": "3"
  },
  {
    "id": 1105,
    "name": "小小",
    "pic": 5,
    "icon": 123,
    "cost": 1,
    "color": 1,
    "hp": 750,
    "attack": 70,
    "armor": 5,
    "race": "4",
    "profession": "0"
  },
  {
    "id": 1106,
    "name": "骨法",
    "pic": 6,
    "icon": 112,
    "cost": 1,
    "color": 1,
    "hp": 500,
    "attack": 65,
    "armor": 10,
    "race": "2",
    "profession": "2"
  },
  {
    "id": 1107,
    "name": "火枪",
    "pic": 7,
    "icon": 104,
    "cost": 1,
    "color": 1,
    "hp": 550,
    "attack": 50,
    "armor": 10,
    "race": "0",
    "profession": "1"
  },
  {
    "id": 1108,
    "name": "骨弓",
    "pic": 8,
    "icon": 105,
    "cost": 1,
    "color": 1,
    "hp": 700,
    "attack": 60,
    "armor": 20,
    "race": "2",
    "profession": "1"
  },
  {
    "id": 1109,
    "name": "屠夫",
    "pic": 9,
    "icon": 106,
    "cost": 1,
    "color": 1,
    "hp": 600,
    "attack": 65,
    "armor": 15,
    "race": "2",
    "profession": "0"
  },
  {
    "id": 1110,
    "name": "冰龙",
    "pic": 10,
    "icon": 124,
    "cost": 1,
    "color": 1,
    "hp": 600,
    "attack": 66,
    "armor": 15,
    "race": "4",
    "profession": "4"
  },
  {
    "id": 1111,
    "name": "水人",
    "pic": 11,
    "icon": 119,
    "cost": 1,
    "color": 1,
    "hp": 750,
    "attack": 70,
    "armor": 5,
    "race": "4",
    "profession": "3"
  },
  {
    "id": 1112,
    "name": "毒龙",
    "pic": 12,
    "icon": 114,
    "cost": 1,
    "color": 1,
    "hp": 500,
    "attack": 65,
    "armor": 10,
    "race": "5",
    "profession": "3"
  },
  {
    "id": 1113,
    "name": "火女",
    "pic": 13,
    "icon": 107,
    "cost": 1,
    "color": 1,
    "hp": 550,
    "attack": 50,
    "armor": 10,
    "race": "0",
    "profession": "2"
  },
  {
    "id": 1114,
    "name": "圣骑",
    "pic": 14,
    "icon": 108,
    "cost": 1,
    "color": 1,
    "hp": 700,
    "attack": 60,
    "armor": 20,
    "race": "0",
    "profession": "0"
  },
  {
    "id": 1115,
    "name": "沙王",
    "pic": 15,
    "icon": 113,
    "cost": 1,
    "color": 1,
    "hp": 600,
    "attack": 65,
    "armor": 15,
    "race": "1",
    "profession": "3"
  },
  {
    "id": 1116,
    "name": "风行",
    "pic": 16,
    "icon": 121,
    "cost": 1,
    "color": 1,
    "hp": 600,
    "attack": 66,
    "armor": 15,
    "race": "3",
    "profession": "5"
  },
  {
    "id": 1118,
    "name": "影魔",
    "pic": 18,
    "icon": 118,
    "cost": 1,
    "color": 1,
    "hp": 750,
    "attack": 70,
    "armor": 5,
    "race": "6",
    "profession": "4"
  },
  {
    "id": 1119,
    "name": "蓝胖",
    "pic": 19,
    "icon": 109,
    "cost": 1,
    "color": 1,
    "hp": 500,
    "attack": 65,
    "armor": 10,
    "race": "1",
    "profession": "2"
  }
];
