'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const rules=require('../game/play/config'),roster=require('../game/play/roster'),{Campaign}=require('../game/play/campaign'),{simulate,random}=require('../game/play/combat');
/** 构造可检查写入和故障回滚的存储端口。 */
function fixture(overrides={}){let saved=null,fail=false;const storage={read:()=>saved?structuredClone(saved):null,write:s=>{if(fail)throw Error('磁盘已满');saved=structuredClone(s);}};const model=new Campaign({...rules,startingGold:300,startingRoster:['zhaoyun','zhangfei','zhangfei','zhangfei'],initialDeployment:[{index:0,slot:8},{index:1,slot:14}],baseDeployedLimit:3,...overrides},roster,storage);return {model,storage,save:()=>structuredClone(saved),fail:()=>{fail=true;}};}
test('自由移动、交换、退阵遵守格子与上阵人数限制',()=>{const {model:m}=fixture();m.deploy(1,14);assert.equal(m.unit(2).slot,8);m.deploy(3,5);assert.throws(()=>m.deploy(4,6),/人数/);m.deploy(4,14);assert.equal(m.unit(1).slot,-1);assert.equal(m.unit(4).slot,14);m.deploy(4,-1);assert.throws(()=>m.deploy(4,18),/己方/);assert.equal(m.unit(4).slot,-1);});
test('原地三合一只消费匹配单位并保留阵位',()=>{const {model:m}=fixture();m.merge(3,'same');assert.equal(m.state.units.length,2);assert.equal(m.unit(3).star,2);assert.equal(m.unit(3).heroId,'zhangfei');assert.equal(m.unit(3).slot,14);assert.equal(m.unit(1).heroId,'zhaoyun');assert.throws(()=>m.merge(1),/三名/);});
test('随机合成可复现，替换身份并保留阶级与站位',()=>{const a=fixture().model,b=fixture().model;a.merge(2,'random');b.merge(2,'random');assert.deepEqual(a.state,b.state);assert.notEqual(a.unit(2).heroId,'zhangfei');assert.equal(a.unit(2).star,2);assert.equal(a.unit(2).slot,14);});
test('招募、缺货、经济不足、满仓均保持原子性',()=>{const {model:m}=fixture({capacity:5});m.recruit(0);const before=structuredClone(m.state);assert.throws(()=>m.recruit(0),/已招募/);assert.throws(()=>m.recruit(1),/容量/);assert.deepEqual(m.state,before);const poor=fixture({startingGold:0}).model;assert.throws(()=>poor.recruit(0),/军资/);assert.throws(()=>poor.refresh(),/军资/);assert.equal(poor.state.gold,0);});
test('存储失败回滚金币、单位、UID、随机种子及格子',()=>{const f=fixture(),before=structuredClone(f.model.state);f.fail();assert.throws(()=>f.model.recruit(0),/磁盘/);assert.deepEqual(f.model.state,before);assert.throws(()=>f.model.merge(2,'random'),/磁盘/);assert.deepEqual(f.model.state,before);assert.deepEqual(f.save(),before);});
test('不同站位参与寻敌，近战移动且不重叠',()=>{const allies=[{uid:1,heroId:'zhaoyun',star:1,slot:0},{uid:2,heroId:'huangzhong',star:1,slot:5}],enemies=[{uid:-1,heroId:'zhangfei',star:1,slot:0}];const a=simulate(allies,enemies,roster,rules,40,1),b=simulate([{...allies[0],slot:5},{...allies[1],slot:0}],enemies,roster,rules,40,1);assert.notDeepEqual(a.events,b.events);assert.ok(a.events.some(e=>e.type==='move'));const live=new Map(a.initial.map(u=>[u.uid,{x:u.x,y:u.y}]));for(const e of a.events){if(e.type==='death')live.delete(e.uid);if(e.type==='move'){const occupied=[...live].some(([uid,p])=>uid!==e.uid&&p.x===e.x&&p.y===e.y);assert.equal(occupied,false);live.set(e.uid,{x:e.x,y:e.y});}}});
test('战斗确定性、有效血量、技能、攻击命中前摇与死亡',()=>{const {model:m}=fixture();const allies=m.state.units.filter(u=>u.slot>=0),enemies=[{uid:-1,heroId:'guanyu',star:2,slot:2}];const a=simulate(allies,enemies,roster,rules,100,1);assert.deepEqual(a,simulate(allies,enemies,roster,rules,100,1));assert.ok(a.events.some(e=>e.type==='attack'&&e.skill));assert.ok(a.events.some(e=>e.type==='death'));for(const hit of a.events.filter(e=>e.type==='damage')){assert.ok(hit.hp>=0&&Number.isFinite(hit.damage));const attack=a.events.find(e=>e.type==='attack'&&e.uid===hit.actor&&e.t<=hit.t-rules.attackDelay+.001);assert.ok(attack);}});
test('待领取战果可跨重启恢复，不能改阵或重复领奖',()=>{const f=fixture();const original=structuredClone(f.model.state.units);const b=f.model.fight();assert.deepEqual(f.model.state.units,original);assert.throws(()=>f.model.deploy(1,3),/结算/);const reloaded=new Campaign(rules,roster,f.storage);assert.deepEqual(reloaded.state.pending.battle,b);const stage=reloaded.state.stage,gold=reloaded.state.gold,reward=reloaded.state.pending.gold;assert.equal(reloaded.claim(0),true);assert.equal(reloaded.state.gold,gold+reward);assert.equal(reloaded.state.stage,stage+1);const snapshot=structuredClone(reloaded.state);assert.equal(reloaded.claim(0),false);assert.deepEqual(reloaded.state,snapshot);});
test('演武不增加经济或推进关卡，战果仍只能领取一次',()=>{const {model:m}=fixture();const gold=m.state.gold,stage=m.state.stage,units=structuredClone(m.state.units);m.fight(true);assert.equal(m.state.pending.choices.length,0);m.claim();assert.equal(m.state.gold,gold);assert.equal(m.state.stage,stage);assert.deepEqual(m.state.units,units);assert.equal(m.state.wins,0);});
test('败局与平局能够结算后重试，满仓可选择只领军资',()=>{const f=fixture({maxBattleSeconds:0}),m=f.model;m.fight();assert.equal(m.state.pending.battle.result,'draw');m.claim();assert.equal(m.state.stage,1);const g=fixture({capacity:4});g.model.fight();assert.throws(()=>g.model.claim(0),/容量/);assert.ok(g.model.state.pending);g.model.claim();assert.equal(g.model.state.stage,2);});
test('损坏存档不静默清空',()=>{const f=fixture(),bad=f.save();bad.units[0].slot=100;assert.throws(()=>new Campaign(rules,roster,{read:()=>bad,write:()=>assert.fail('不能覆盖损坏存档')}),/损坏/);});
test('相邻种子不会把首个随机结果集中到同一武将',()=>{const counts=Array(roster.length).fill(0);for(let seed=1;seed<=1000;seed++)counts[Math.floor(random(seed)()*roster.length)]++;assert.ok(counts.every(n=>n>100&&n<300));});
