'use strict';
const c=require('./activity-config'),l=c.layout;
/** 图片按钮共用点击隔离和文字大小，保持纸张与红金按钮的视觉体系。 */
function button(v,parent,text,x,y,width,action,color='red',height=62){const n=v.ui.node(parent,text,x,y,width,height);v.ui.image(n,'classic/button-'+color+'.png',0,0,width,height);require('./button-content').draw(v.ui,n,text,l.font,'#FFE267',width-12,height-8);n.on(v.cc.Node.EventType.TOUCH_END,e=>{e.propagationStopped=true;action();});return n;}
/** 弹窗内阻止触摸穿透，点遮罩保留原页面并关闭。 */
function modal(v,title){const shade=v.overlay(),p=v.paper(shade,'activity-panel',0,0,l.modalWidth,l.modalHeight);p.addComponent(v.cc.BlockInputEvents);require('./paper-title').draw(v,p,title,l.modalWidth,l.modalHeight);v.ui.text(shade,c.text.close,0,-l.modalHeight/2-30,26,'#FFFFFF',600,40);shade.on(v.cc.Node.EventType.TOUCH_END,e=>{e.propagationStopped=true;if(e.target===shade){shade.destroy();v.modal=null;}});return p;}
/** 奖励图标显示真实物品数量，未知随机碎片以问号表达其类别。 */
function rewards(v,p,items,y=l.rewardY){Object.entries(items).forEach(([id,count],i)=>{const x=l.rewardX+i*l.rewardGap,n=v.ui.box(p,'reward-'+id,x,y,l.iconSize,l.iconSize,'#362344');v.ui.image(n,id==='1'?'classic/diamond.png':'classic/item-'+id+'.png',0,4,67,67);v.ui.text(n,id==='1'?require('./vip').diamonds(v.model,count):count,9,-24,24,'#FFFFFF',64,32);});}
/** 切页只销毁当前弹窗，不切换宿主页面。 */
function tabs(v,p,names,selected,select){const width=(l.modalWidth-60)/names.length;names.forEach((name,i)=>{const n=button(v,p,name,(i-(names.length-1)/2)*width,l.tabY,width-10,()=>select(i),i===selected?'gold':'blue',62);if(name===c.text.daily||name===c.text.sign)require('./notification-view').badge(v,n,'daily-tab-'+i,width/2-18,26,()=>name===c.text.sign?!require('./sign-rewards').status(v.progress).today:v.model.activities.daily().some(t=>!t.claimed&&t.count>=t.target));});}
/** 统一分享管理器返回软校验结果，再由场景服务原子完成任务或发奖。 */
function share(v,source='invite'){const service=require('./share-rewards'),registry=require('./share-scenarios'),model=v.model;if(!service.available(model,source)){v.notice('分享',registry.text.limit);return;}const token=service.ticket(model);try{if(!v.shareService){v.shareService=new (require('./share-service').ShareService)(typeof wx==='undefined'?null:wx);}v.shareService.request(source,result=>{if(v.model!==model)return;if(!result.ok){v.notice('分享未完成',registry.text[result.reason]||registry.text.failed);return;}try{const items=service.complete(model,source,token);v.render();if(source==='daily')daily(v);else invite(v);if(Object.keys(items).length)require('./activity-reward-view').show(v,items);require('./notification-view').refresh(v);}catch(error){v.notice('分享奖励',error.message);}});}catch(error){v.notice('暂时无法分享',error.message);}}
/** 日常进度来自实际结算事件，领取和双倍回调都重新验证条件。 */
function daily(v,tab=0){const p=modal(v,tab?c.text.sign:c.text.daily),u=v.ui,a=v.model.activities;if(tab){require('./sign-view').render(v,p,button,()=>daily(v,1));}else a.daily().forEach((t,i)=>{const row=v.ui.box(p,'daily-'+t.id,0,l.rowTop-i*l.rowGap,l.rowWidth,l.rowHeight,'#DFCEA7');u.text(row,t.name,-65,53,28,'#674322',470,42);rewards(v,row,c.rewards);if(!t.claimed&&t.count>=t.target)require('./notification-view').badge(v,row,'daily-'+t.id,l.rowWidth/2-12,l.rowHeight/2-12,()=>v.model.activities.daily().some(x=>x.id===t.id&&!x.claimed&&x.count>=x.target));if(t.claimed)u.text(row,'已领取',l.actionX,-10,28,'#796948',180,65);else if(t.count>=t.target){button(v,row,'领取奖励',l.actionX,9,l.buttonWidth,()=>claimDaily(v,t.id),'red',52);const ticket=a.ticket();button(v,row,'▶ 双倍领取',l.actionX,-50,l.buttonWidth,()=>claimDaily(v,t.id,ticket), 'gold',52);}else if(t.id==='share')button(v,row,'分享',l.actionX,-9,l.buttonWidth,()=>share(v,'daily'));else u.text(row,'当前进度\n('+Math.min(t.count,t.target)+'/'+t.target+')',l.actionX,-18,26,'#674322',180,88);});tabs(v,p,[c.text.daily,c.text.sign],tab,i=>daily(v,i));}
/** 邀请页展示软校验分享次数及已入库奖励，不将次数冒充不同好友人数。 */
function invite(v,tab=0){const p=modal(v,c.invite.tabs[tab]),u=v.ui,service=require('./share-rewards'),state=service.status(v.model),registry=require('./share-scenarios');if(tab===0){const banner=u.box(p,'invite-banner',0,301,590,136,'#29484D');u.image(banner,'zhouyu-avatar.png',225,0,114,114);u.text(banner,'邀请好友',-60,28,39,'#F7D655',410,60);u.text(banner,registry.text.note.replace('{0}',registry.scenarios.invite.limit),-40,-31,23,'#FFFFFF',460,44);[{title:'首次邀请分享',count:0,reward:c.invite.shareRewards},...c.invite.targets.map(n=>({title:'邀请分享'+n+'次',count:n,reward:c.invite.rewards}))].forEach((r,i)=>{const row=u.box(p,'invite-row-'+i,0,151-i*151,604,143,'#DFCEA7');u.text(row,r.title,-130,44,27,'#674322',300,40);rewards(v,row,r.reward,-25);const claimed=r.count?state.milestones.includes(r.count):state.shareReward;if(r.count)u.text(row,Math.min(state.inviteCount,r.count)+'/'+r.count,l.actionX,24,24,'#674322',150,35);if(claimed)u.text(row,'已领取',l.actionX,-33,27,'#527E32',l.buttonWidth,55);else button(v,row,'邀请分享',l.actionX,-33,l.buttonWidth,()=>share(v),'red',55);});}else{u.text(p,tab===1?registry.text.newcomer:c.text.group,0,70,30,'#674322',560,300);if(tab===1)button(v,p,'邀请好友',0,-170,270,()=>share(v,'newcomer'));}tabs(v,p,c.invite.tabs,tab,i=>invite(v,i));}
/** 天赋八项围绕轮盘排列，点图标查看当前等级与真实伤害增减说明。 */
function talent(v){const u=v.ui,a=v.model.activities,s=a.state.talent;u.image(v.root,'classic/talent-board.png',0,l.wheelY,l.wheelWidth,l.wheelHeight);u.text(v.root,'天赋等级：'+s.level,0,415,36,'#F9EDD2',560,60);c.talent.entries.forEach((e,i)=>{const angle=Math.PI/2-i*Math.PI/4,x=Math.cos(angle)*l.wheelRadius,y=l.wheelY+Math.sin(angle)*l.wheelRadius,n=u.node(v.root,'talent-'+i,x,y,l.wheelIcon,l.wheelIcon);u.image(n,'classic/avatar-frame.png',0,0,l.wheelIcon+16,l.wheelIcon+16);u.image(n,'equipment/'+e[3]+'.png',0,0,l.wheelIcon-20,l.wheelIcon-20);u.text(n,e[0],0,-70,28,'#FFFFFF',135,45);u.box(n,'rank',45,-39,42,42,'#35251A');u.text(n,s.levels[i],45,-39,26,'#F4E3C8',42,42);n.on(v.cc.Node.EventType.TOUCH_END,()=>v.notice(e[0]+' Lv.'+s.levels[i],'所有己方单位'+e[1]+' '+Math.round(s.levels[i]*c.talent.step*100)+'%\n每级提升 '+Math.round(c.talent.step*100)+'%'));});const center=u.node(v.root,'talent-points',0,l.wheelY,145,145);require('./talent-orb').draw(v,center,a.fill());u.text(center,'加 点',0,0,35,'#FFFFFF',130,65);center.on(v.cc.Node.EventType.TOUCH_END,()=>require('./talent-tree-view').open(v));require('./notification-view').badge(v,center,'tree',68,68);u.text(v.root,'每个天赋概率相同，效果作用于所有己方单位',0,-358,24,'#FFFFFF',670,60);const paid=button(v,v.root,'',a.canBreak()?l.singleActionX:l.leftActionX,-449,285,()=>require('./talent-animation').enhance(v),'blue',103);paid.name='talent-enhance';u.text(paid,a.canBreak()?'突破':'强化',0,l.actionTitleY,l.font,'#FFE267',260,40);u.image(paid,'classic/diamond.png',l.costIconX,l.costY,l.costIconSize,l.costIconSize);u.text(paid,a.cost(),l.costTextX,l.costY,l.font,'#FFE267',120,40);require('./notification-view').badge(v,paid,'enhance',l.actionBadgeX,l.actionBadgeY);if(!a.canBreak()){const used=a.state.day===a.day()?a.state.adUsed:0,ticket=a.ticket();button(v,v.root,used<c.talent.adLimit?'▶ 免费\n今日剩余'+(c.talent.adLimit-used)+'次':'军略丹强化\n消耗 '+c.talent.dustCost,l.rightActionX,-449,285,()=>require('./talent-animation').enhance(v,used<c.talent.adLimit?'ad':'dust',ticket),'gold',103);}}
/** 仅成功入库后展示回执；关闭回执返回日常，失败不显示成功奖励。 */
function claimDaily(v,id,ticket=null){let receipt=null;const done=()=>{receipt=null;receipt=v.model.activities.claim(id,ticket);},after=()=>{if(!receipt)return;daily(v);require('./activity-reward-view').show(v,receipt);require('./notification-view').refresh(v);};if(ticket)v.ad(done,after);else{v.act(done);after();}}
module.exports={daily,invite,talent,claimDaily,share};
