'use strict';
const c=require('./defeat-config'),blessing=require('./lord-blessing-config');
/** 金边切角对话框与侧边指示角，复用原版的暖纸色与布局。 */
function bubble(v,parent,name,x,y,w,h,text){const u=v.ui,cc=v.cc,n=u.node(parent,name,x,y,w,h),g=n.addComponent(cc.Graphics),corner=10;g.fillColor=new cc.Color(c.bubbleFill);g.strokeColor=new cc.Color(c.bubbleBorder);g.lineWidth=5;g.moveTo(-w/2+corner,h/2);g.lineTo(w/2-corner,h/2);g.lineTo(w/2,h/2-corner);g.lineTo(w/2,-h/2+corner);g.lineTo(w/2-corner,-h/2);g.lineTo(-w/2+corner,-h/2);g.lineTo(-w/2,-h/2+corner);g.lineTo(-w/2,h/4);g.lineTo(-w/2-28,h/4+26);g.lineTo(-w/2,h/4+26);g.lineTo(-w/2,h/2-corner);g.close();g.fill();g.stroke();u.text(n,text,5,0,c.font,'#593923',w-38,h-18);return n;}
/** 红金按钮共用真实结算入口，广告取消时保留待处理战果。 */
function button(v,parent,label,x,color,action){const u=v.ui,n=u.node(parent,label,x,c.buttonY,c.buttonWidth,c.buttonHeight);u.image(n,'classic/button-'+color+'.png',0,0,c.buttonWidth,c.buttonHeight);require('./button-content').draw(u,n,label,33,'#FFE260',c.buttonWidth-12,c.buttonHeight);n.on(v.cc.Node.EventType.TOUCH_END,e=>{e.propagationStopped=true;action();});}
/** 普通远征战败保留战场背景，显示扣血后生命、主公劝告与甄姬提醒。 */
function show(v,p){if(v.progress.state.hp<=1)return require("./revive-view").show(v,p);const u=v.ui,m=v.overlay(),hp=Math.max(0,v.progress.state.hp-1),lord=v.progress.lord();u.box(m,'defeat-panel',0,c.panelY,720,c.panelHeight,'#14343EEF',false);const title=u.text(m,c.title,0,c.titleY,c.titleFont,'#90CFFF',700,80);title.enableOutline=true;title.outlineColor=new v.cc.Color('#223D62');title.outlineWidth=4;u.portrait(m,lord.portrait,c.portraitX,c.portraitY,c.portraitWidth,c.portraitHeight,require('./classic-config').portraitCrop);u.text(m,'等级 '+v.model.state.expedition.level,c.portraitX,c.levelY,28,'#FFFFFF',160,38);u.text(m,'♥'.repeat(hp)+'♡'.repeat(Math.max(0,lord.hp-hp)),c.portraitX,c.heartsY,32,'#E76761',190,44);bubble(v,m,'lord-defeat-advice',c.bubbleX,c.bubbleY,c.bubbleWidth,c.bubbleHeight,c.advice);u.text(m,c.hint,0,c.hintY,31,'#FF6464',685,48);const claim=require('./defeat-reward').claim;button(v,m,c.continue,hp?-c.buttonX:0,'red',()=>v.act(()=>claim(v.model,p.id)));if(hp){const ticket=v.model.adTicket();button(v,m,c.blessing,c.buttonX,'gold',()=>{let receipt;v.ad(()=>{receipt=claim(v.model,p.id,ticket);},()=>require('./lord-blessing-view').show(v,receipt));});u.text(m,blessing.description,c.buttonX,c.rewardY,26,'#FFFFFF',325,42);}bubble(v,m,'defeat-guide',c.guideX,c.guideY,c.guideWidth,c.guideHeight,c.guide);u.actor(m,{uid:'defeat-guide',heroId:c.npc,star:1,side:'enemy'},c.npcX,c.npcY,c.npcScale,false);return m;}
module.exports={show};
