'use strict';
const c=require('./equipment-effect-config');
/** 只取真实穿戴物；效果实例保留物品UID用于跨战斗成长。 */
function entries(u){return u.equipmentRuntime||[];}
/** 属性阶段补齐基础属性之外的静态效果和已保存的击杀成长。 */
function stats(result,unit,units,equipment){const team=new Set(units.map(u=>u.uid));result.equipmentRuntime=[];for(const item of equipment){const s=c[item.id];if(!s||!team.has(item.owner)||!require('./equipment-exclusive').active(item.id,units.find(u=>u.uid===item.owner)?.heroId))continue;if(s.teamAttack)result.attack*=1+s.teamAttack;if(item.id==='7203')result.armor+=s.armor;if(s.teamCooldown)result.equipmentCooldown=(result.equipmentCooldown||0)+s.teamCooldown;if(s.teamLeech&&result.range<=1)result.leech+=s.teamLeech;if(item.owner!==unit.uid||s.exclusive&&!s.exclusive.includes(unit.heroId))continue;const stacks=item.stacks||0;if(!result.equipmentRuntime.some(e=>e.id===item.id))result.equipmentRuntime.push({id:item.id,uid:item.uid,stacks,next:s.initialCooldown??s.period??0});if(s.leech)result.leech+=s.leech;if(s.dodge)result.bondDodge=Math.max(result.bondDodge||0,s.dodge);if(s.magicPen)result.magicPen+=s.magicPen;if(item.id==='7105'){result.regen+=s.regen;result.regenPercent+=s.regenPercent;}if(item.id==='7205')result.regen+=s.regen;if(s.killAttack)result.attack+=stacks*s.killAttack;}}
/** 战斗初始化统一应用冷却缩减，计时器和实际重复施法共享倍率。 */
function initialize(units){for(const u of units){const factor=Math.max(.1,1-(u.equipmentCooldown||0));u.cooldownFactor*=factor;u.nextSkill*=factor;for(const id of Object.keys(u.skillTimers||{}))u.skillTimers[id]*=factor;u.equipmentJobs=[];u.equipmentDeaths=0;u.equipmentGold=0;}}
/** 发出与真实属性变化对应的绿色增益提示。 */
function gain(events,u,t,text,effect){events.push({type:'gain',t,target:u.uid,text,effect});}
/** 沉默禁止装备主动技能；伤害和治疗延迟任务仍可按既定时间执行。 */
function tick(a,units,t,events,heal,damage,rng){const allies=units.filter(u=>u.hp>0&&u.side===a.side),enemies=units.filter(u=>u.hp>0&&u.side!==a.side);for(const source of enemies)if(entries(source).some(e=>e.id==='7108'))a.auraSlow=Math.max(a.auraSlow||0,c['7108'].auraSlow);if(a.equipmentSlowUntil>t)a.auraSlow=Math.max(a.auraSlow||0,a.equipmentSlow||0);if(a.hp<=0)return;for(const j of a.equipmentJobs||[])while(j.left>0&&j.next<=t){j.next++;j.left--;if(j.u.hp>0){if(j.heal)heal(j.u,j.heal,t);else damage(a,j.u,j.damage,t,true,false,false);}}a.equipmentJobs=(a.equipmentJobs||[]).filter(j=>j.left>0);const skills=require('./hero-skills');for(const e of entries(a)){const s=c[e.id];if(e.id==='7004'&&e.until>t){if((e.drainAt||0)<=t){e.drainAt=t+1;damage(a,a,s.drain,t,true,false,false,'healthLoss');}}if(!s.period||t<e.next||a.silencedUntil>t||!enemies.length)continue;e.next=t+s.period*(s.exclusive?1:a.cooldownFactor);const target=['7109','7111'].includes(e.id)?enemies[Math.floor(rng()*enemies.length)]:e.id==='7110'?enemies.slice().sort((x,y)=>y.attack-x.attack)[0]:enemies.slice().sort((x,y)=>Math.abs(x.x-a.x)+Math.abs(x.y-a.y)-Math.abs(y.x-a.x)-Math.abs(y.y-a.y))[0];if(e.id!=='7214')events.push({type:'equipment',t,uid:a.uid,target:target.uid,id:e.id});switch(e.id){case '7214':for(const u of allies){skills.buff(u,'equip-march',{skillHaste:s.haste,marchMove:s.move,marchCast:s.cast},t+s.duration);events.push({type:'equipment',t,uid:a.uid,target:u.uid,id:e.id,duration:s.duration});}break;case '7004':skills.buff(a,'equip-rage',{attack:s.attack,skillHaste:s.haste,maxHp:s.hp,regen:s.regen,armor:s.armor},t+s.duration);e.until=t+s.duration;e.drainAt=t+1;gain(events,a,t,'攻击 +35');break;case '7010':for(const u of enemies)damage(a,u,s.damage,t,true,false,false);break;case '7102':for(const u of allies){for(const id of Object.keys(u.skillTimers))u.skillTimers[id]=Math.max(t,u.skillTimers[id]-s.seconds);u.nextSkill=Math.max(t,u.nextSkill-s.seconds);for(const item of entries(u))if(!c[item.id]?.exclusive)item.next=Math.max(t,item.next-s.seconds);gain(events,u,t,'冷却 -2秒','mana');}break;case '7103':target.stunnedUntil=Math.max(target.stunnedUntil||0,t+s.stun);events.push({type:'status',t,target:target.uid,effect:'stun',duration:s.stun});break;case '7109':{const u=target;u.silencedUntil=Math.max(u.silencedUntil||0,t+s.duration);events.push({type:'status',t,target:u.uid,effect:'silence',duration:s.duration});a.equipmentJobs.push({u,damage:s.damage,next:t+1,left:s.duration});break;}case '7110':{const u=target;damage(a,u,(s.damage+e.stacks*s.killDamage)*100/(100+Math.max(-60,u.magicArmor-(a.magicPen||0))),t,true,false,false);break;}case '7111':{const u=target;u.stunnedUntil=Math.max(u.stunnedUntil||0,t+s.duration);u.silencedUntil=Math.max(u.silencedUntil||0,t+s.duration);events.push({type:'status',t,target:u.uid,effect:'hex',duration:s.duration});break;}}if(!s.exclusive&&entries(a).some(x=>x.id==='7112')&&rng()<c['7112'].chance)e.next=t;}}
/** 暴击装备直接放大本次暴击倍率。 */
function critical(a,rng){return entries(a).some(e=>e.id==='7006')&&rng()<c['7006'].chance?c['7006'].multiplier:1;}
/** 命中效果只处理真实普攻，不让溅射或闪电递归触发。 */
function hit(a,u,amount,t,units,events,heal,damage,rng){const skills=require('./hero-skills');for(const e of entries(a)){const s=c[e.id];if(e.id==='7003'&&a.range<=1)for(const v of units.filter(v=>v.hp>0&&v.side!==a.side&&v.uid!==u.uid&&Math.max(Math.abs(v.x-u.x),Math.abs(v.y-u.y))<=1))damage(a,v,amount*s.splash,t,true,false,false,'equipment-7003');if(e.id==='7005'&&u.hp>0){events.push({type:'status',t,target:u.uid,effect:'armorBreak',duration:s.duration});skills.buff(u,'equip-maim',{attack:s.attack,armor:s.armor},t+s.duration);u.equipmentSlow=s.slow;u.equipmentSlowUntil=t+s.duration;}if(e.id==='7107'&&u.hp>0){events.push({type:'status',t,target:u.uid,effect:'slow',duration:s.duration});skills.buff(u,'equip-frost',{cooldownFactor:s.cooldown},t+s.duration);u.equipmentSlow=Math.max(u.equipmentSlow||0,s.slow);u.equipmentSlowUntil=t+s.duration;}if(e.id==='7114'&&rng()<s.chance){const targets=units.filter(v=>v.hp>0&&v.side!==a.side).map(v=>({v,key:rng()})).sort((x,y)=>x.key-y.key).slice(0,s.targets).map(x=>x.v);for(const v of targets)damage(a,v,s.damage*100/(100+Math.max(-60,v.magicArmor-(a.magicPen||0))),t,true,false,false,'equipment-7114');events.push({type:'equipment',t,uid:a.uid,target:u.uid,targets:targets.map(v=>v.uid),id:e.id});}if(e.id==='7209'){e.hits=e.target===u.uid?Math.min(s.maxStacks,(e.hits||0)+1):1;e.target=u.uid;a.equipmentHaste=e.hits*s.haste;gain(events,a,t,'攻速 +'+Math.round(a.equipmentHaste*100)+'%');}}
if(entries(u).some(e=>e.id==='7108')&&a.hp>0){a.equipmentSlow=c['7108'].slow;a.equipmentSlowUntil=t+c['7108'].duration;}}
/** 吸血溢出独立形成护盾，不增加生命上限。 */
function leech(a,amount,t,events){if(!entries(a).some(e=>e.id==='7007'))return;const overflow=Math.max(0,amount-(a.maxHp-a.hp));if(overflow){const before=a.equipmentShield||0;a.equipmentShield=Math.min(a.maxHp*c['7007'].shieldCap,before+overflow);if(a.equipmentShield>before)gain(events,a,t,'护盾 +'+Math.round(a.equipmentShield-before),'shield');}}
/** 击杀成长按装备实例保存；非召唤物死亡驱动葫芦、金币与击杀层数。 */
function death(dead,killer,units,t,events){if(dead.summoned)return;for(const a of units){for(const e of entries(a)){const s=c[e.id];if(a===dead&&s.maxStacks){e.stacks=Math.floor(e.stacks/2);continue;}if(a.hp<=0)continue;if(e.id==='7010'&&killer.side===a.side&&dead.side!==a.side)a.equipmentGold+=s.gold;if(a===killer&&dead.side!==a.side&&['7009','7110'].includes(e.id)&&e.stacks<s.maxStacks){e.stacks++;if(s.killAttack)a.attack+=s.killAttack;gain(events,a,t,'击杀强化 +1');}if(e.id==='7106'){a.equipmentDeaths++;const good=a.equipmentDeaths%2===1,pool=units.filter(u=>u.hp>0&&(good?u.side===a.side:u.side!==a.side)).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp);if(pool[0])a.equipmentJobs.push({u:pool[0],heal:good?s.heal:0,damage:s.damage,next:t+1,left:s.duration});}}}}
/** 本体技能施放完成后独立判定刷新，仅清除本次技能冷却。 */
function cast(a,id,t,rng,events){if(entries(a).some(e=>e.id==='7112')&&rng()<c['7112'].chance){a.skillTimers[id]=t;gain(events,a,t,'技能刷新','mana');}}
/** 导出玩家装备成长及胜利金币，领取战果时一次性写入。 */
function receipt(units,result){const allies=units.filter(u=>u.side==='ally');return {equipmentProgress:allies.flatMap(u=>entries(u).filter(e=>['7009','7110'].includes(e.id)).map(e=>({uid:e.uid,stacks:e.stacks}))),equipmentGold:result==='win'?allies.reduce((n,u)=>n+(u.equipmentGold||0)+entries(u).filter(e=>e.id==='7210').reduce((sum,e)=>sum+c[e.id].winGold,0),0):0};}
module.exports={stats,initialize,tick,critical,hit,leech,death,cast,receipt};
