"use strict";
/** 远征本地规则集中维护；掉落权重与模拟数值属于本地策略。 */
module.exports = {
  equipmentLimit: 3,
  rankLimit: 4,
  maxStar: 5,
  fiveStarChapter: 18,
  choiceCount: 3,
  refreshRank: 2,
  enemyRankEveryStages: 5,
  experience: {
    normal: 100,
    elite: 200,
    thresholds: [90, 300, 600, 1000, 1500],
  },
  directedAfterFirstNode: true,
  initialRoster: ["xuchu", "xuchu", "xuchu"],
  models: ["zhaoyun", "zhangfei", "guanyu", "huangzhong", "zhugeliang"],
  novice: [
    { kind: "hero", id: "guanyu", star: 3 },
    { kind: "equipment", id: "7212" },
    { kind: "diamonds", count: 10000 },
  ],
  elitePool: [
    "7201",
    "7202",
    "7204",
    "7206",
    "7207",
    "7208",
    "7211",
    "7212",
    "7213",
  ],
  equipment: [
    {
      id: "7201",
      name: "反甲",
      symbol: "甲",
      description: "受到物理伤害时反弹25%。",
      reflect: 0.25,
    },
    {
      id: "7202",
      name: "战鼓",
      symbol: "鼓",
      description: "全体友军攻击速度提高6%。",
      teamHaste: 0.06,
    },
    {
      id: "7204",
      name: "烟斗",
      symbol: "御",
      description: "全体友军魔防提高6，每秒回复8生命。",
      teamMagicArmor: 6,
      teamRegen: 8,
    },
    {
      id: "7206",
      name: "先锋盾",
      symbol: "盾",
      description: "每次受到伤害抵挡40点。",
      block: 40,
    },
    {
      id: "7207",
      name: "头巾",
      symbol: "巾",
      description: "受到伤害降低20%。",
      reduction: 0.2,
    },
    {
      id: "7208",
      name: "疯脸",
      symbol: "嗜",
      description: "物理攻击吸血17%。",
      leech: 0.17,
    },
    {
      id: "7211",
      name: "梅肯",
      symbol: "愈",
      description: "全体每秒回复8生命，每8秒回复150生命。",
      teamRegen: 8,
      teamHeal: 150,
      healInterval: 8,
    },
    {
      id: "7212",
      name: "龙心",
      symbol: "心",
      description: "最大生命提高15%，每秒回复2%最大生命。",
      hpPercent: 0.15,
      regenPercent: 0.02,
    },
    {
      id: "7213",
      name: "强袭",
      symbol: "铠",
      description: "全体友军物理防御提高15。",
      teamArmor: 15,
    },
  ],
  colors: ["#36A83B", "#398DDD", "#A34DDC", "#E7A23A", "#E75938"],
  layout: {
    cardWidth: 334,
    cardHeight: 960,
    cardY: 30,
    portrait: 130,
    skillFont: 22,
    detailWidth: 420,
    detailHeight: 1060,
  },
  localCombat: {
    interval: 1.5,
    skillEvery: 3,
    skillPower: 1.5,
    armorFloor: -80,
  },
  primarySkills: {
    zhenji: { power: 1.2, radius: 1, slow: 0.5, duration: 4 },
    xuchu: { passive: "counter", chance: 0.35, power: 0.35, radius: 1 },
    xiahouyuan: { passive: "slow", slow: 0.2, duration: 2 },
    zhaoyun: { passive: "delay", delay: 3 },
    dianwei: { power: 1.5, radius: 1 },
    diaochan: { power: 1, drain: true },
    huangzhong: { passive: "bash", chance: 0.4, power: 1.15, stun: 0.2 },
    taishici: { passive: "bonus", power: 1.5 },
    zhangfei: { power: 1.5, farthest: true, pull: true, trueDamage: true },
    xiaoqiao: { power: 3, highestHp: true, radius: 1, slow: 0.25, duration: 4 },
    ganning: { power: 1.5, line: true },
    zhangliao: { power: 1.2, magicBreak: 30, duration: 3 },
    zhouyu: { power: 1.2, radius: 1, stun: 2 },
    guanyu: { heal: 1.2 },
    machao: { power: 1.5, line: true, stun: 2 },
    sunshangxiang: { power: 0.5, line: true, stun: 3 },
    zhangjiao: { power: 2.4, radius: 1 },
    yanliang: { power: 2, radius: 1, selfCenter: true },
    huangyueying: { power: 0.25, radius: 1 },
    zhurong: { power: 2.5, armorBreak: 20, duration: 4 },
    lvbu: { power: 1.2, line: true, stun: 1 },
  },
};
