'use strict';
const {Handbook}=require('./handbook');
/** 独立图鉴弹窗，仅消费查询结果，不通过页面跳转重建地图。 */
class HandbookView{
 /** 保存宿主渲染服务与图鉴内部状态，不复制或写入玩家数据。 */
 constructor(host){this.host=host;this.cc=host.cc;this.ui=host.ui;this.book=new Handbook();this.config=this.book.config;this.layout=this.config.layout;this.tab='heroes';this.offsets={heroes:0,equipment:0,bonds:0};this.selected=null;this.dragged=false;}
 /** 创建覆盖层并保持原页面节点、地图偏移和玩家状态不变。 */
 open(){this.modal=this.host.overlay();this.modal.name='handbook-modal';this.modal.on(this.cc.Node.EventType.TOUCH_END,e=>{const point=e.getUILocation(),p=this.modal.getComponent(this.cc.UITransform).convertToNodeSpaceAR(new this.cc.Vec3(point.x,point.y,0));if(Math.abs(p.x)>this.layout.width/2||Math.abs(p.y)>this.layout.height/2)this.close();});this.render();}
 /** 销毁自身弹窗，解除宿主引用；不调用战役保存或页面重绘。 */
 close(){if(this.modal?.isValid)this.modal.destroy();if(this.host.modal===this.modal)this.host.modal=null;this.host.handbook=null;require("./notification-view").refresh(this.host);}
 /** 重新绘制弹窗内部；外层底图和触摸阻挡始终保留。 */
 render(){for(const child of [...this.modal.children]){child.removeFromParent();child.destroy();}const l=this.layout,u=this.ui;this.panel=this.host.paper(this.modal,'handbook-panel',0,0,l.width,l.height);this.panel.addComponent(this.cc.BlockInputEvents);require('./paper-title').draw(this.host,this.panel,this.selected?this.book.hero(this.selected).name:this.config.tabs.find(t=>t[0]===this.tab)[1],l.width,l.height);u.text(this.modal,this.config.text.close,0,-l.height/2-40,l.font,'#FFFFFF').node.name='handbook-close-hint';if(this.selected)this.detail();else{this.tabs();if(this.tab==='heroes')this.heroes();else if(this.tab==='bonds')this.bonds();else require('./equipment-catalog-view').render(this);}}
 /** 页签仅切换图鉴内容，分别保留武将和羁绊的滚动位置。 */
 tabs(){const l=this.layout;this.config.tabs.forEach(([id,name],i)=>{const button=this.ui.button(this.panel,name,(i-1)*210,l.tabY,195,()=>{this.tab=id;this.selected=null;this.render();},this.tab===id?l.gold:'#967A57',66);if(id==='equipment'||id==='bonds')require('./notification-view').badge(this.host,button,id,84,27);});}
 /** 有界滚动视口统一识别拖动，避免滑动结束误打开武将详情。 */
 viewport(height){const l=this.layout,cc=this.cc,n=this.ui.node(this.panel,'handbook-scroll',0,l.viewportY,l.viewportWidth,l.viewportHeight);n.addComponent(cc.Mask);const max=Math.max(0,height-l.viewportHeight),offset=Math.max(0,Math.min(max,this.offsets[this.tab]||0));const content=this.ui.node(n,'handbook-content',0,offset,l.viewportWidth,height);let start=null,base=offset;this.offsets[this.tab]=offset;n.on(cc.Node.EventType.TOUCH_START,e=>{start=e.getUILocation();base=content.position.y;this.dragged=false;});n.on(cc.Node.EventType.TOUCH_MOVE,e=>{if(!start)return;const delta=e.getUILocation().y-start.y;if(Math.abs(delta)>l.dragThreshold)this.dragged=true;const next=Math.max(0,Math.min(max,base+delta));content.setPosition(0,next,0);this.offsets[this.tab]=next;});return content;}
 /** 复用模型立绘时按配置截取头肩区域，不改写原图片或战斗外观。 */
 face(parent,hero,x,y,size){return hero.portraitRegion?this.ui.portrait(parent,hero.portrait,x,y,size,size,hero.portraitRegion):this.ui.image(parent,hero.portrait,x,y,size,size);}
 /** 绘制有明确身份的头像，尚未满足条件时使用锁定提示而非替换头像。 */
 portrait(parent,hero,x,y,size){const status=this.book.status(hero,this.host.progress.state,this.host.roster),n=this.ui.node(parent,'portrait-'+hero.id,x,y,size,size);this.ui.box(n,'portrait-frame',0,0,size+6,size+6,'#796548');this.face(n,hero,0,0,size);if(status.locked)require('./lock-view').show(this,n,0,0,size*require('./lock-view').config.portraitRatio);n.on(this.cc.Node.EventType.TOUCH_END,e=>{e.propagationStopped=true;if(!this.dragged){require('./handbook-detail').show(this,hero.id);}});return n;}
 /** 按最低阶分行展示21个角色，阶级不是重复的人物条目。 */
 heroes(){const l=this.layout,groups=this.book.groups(),heights=groups.map(g=>l.tierHeader+Math.ceil(g.heroes.length/l.columns)*l.cellHeight+l.padding),total=heights.reduce((a,b)=>a+b,0)+110,content=this.viewport(total);let y=l.viewportHeight/2-l.padding;groups.forEach((group,index)=>{const h=heights[index],row=this.ui.box(content,'tier-'+group.tier,0,y-h/2,l.viewportWidth-8,h-10,l.paper);this.ui.text(row,group.tier+'阶',-255,h/2-31,28,l.colors[index],85,48);group.heroes.forEach((hero,i)=>{const x=(i%l.columns-(l.columns-1)/2)*l.cellWidth,cy=h/2-l.tierHeader-l.portrait/2-Math.floor(i/l.columns)*l.cellHeight;this.portrait(row,hero,x,cy,l.portrait);this.ui.text(row,hero.name,x,cy-l.portrait/2-20,l.font,l.ink,l.cellWidth,36);if(hero.unlock!=='initial')this.ui.text(row,this.book.listCondition(hero),x,cy-l.portrait/2-51,19,l.muted,l.cellWidth,45);});y-=h;});this.ui.text(content,this.book.format(this.config.text.fiveStar,[this.config.fiveStarChapter]),0,y-42,l.font,l.ink,l.viewportWidth,90);}
 /** 羁绊卡片从查询层派生成员，明确标注预览而不宣称已经生效。 */
 bonds(){const l=this.layout,pending=require('./bond-activation-config').entries.filter(e=>!require('./bond-activation').state(this.host.model).includes(e.id)),bonds=this.book.bonds().filter(b=>!pending.some(e=>e.id===b.id)),content=this.viewport(bonds.length*l.bondHeight+pending.length*require('./bond-activation-config').layout.height+105);let y=l.viewportHeight/2-l.padding;pending.forEach(e=>{require("./bond-activation-view").render(this,content,y,e);y-=require("./bond-activation-config").layout.height;});bonds.forEach(b=>{const n=this.ui.box(content,'bond-'+b.id,0,y-l.bondHeight/2,l.viewportWidth-8,l.bondHeight-12,l.paper);this.ui.text(n,b.name+'  ·  '+(b.thresholds||this.config.thresholds).join('／')+'人',0,132,29,l.ink,600,40);this.ui.text(n,b.description,0,86,22,l.ink,584,58);b.members.forEach((h,i)=>{const x=(i%l.bondColumns-1)*l.cellWidth,cy=16-Math.floor(i/l.bondColumns)*l.bondRow;this.portrait(n,h,x,cy,l.bondPortrait);this.ui.text(n,h.name,x,cy-l.bondPortrait/2-19,22,l.ink,l.cellWidth,32);});y-=l.bondHeight;});}
 /** 人物详情仅展示图鉴定位和条件，不展示虚构的战斗属性或购买按钮。 */
 detail(){const l=this.layout,h=this.book.hero(this.selected),status=this.book.status(h,this.host.progress.state,this.host.roster),u=this.ui;this.face(this.panel,h,0,239,232);u.text(this.panel,this.book.condition(h),0,0,26,l.ink,570,90);u.text(this.panel,status.label,0,-91,25,status.available?'#40734B':'#A7482A',570,75);const bonds=this.book.bonds().filter(b=>b.members.some(m=>m.id===h.id));u.text(this.panel,bonds.map(b=>b.name+'：'+b.description).join('\n\n'),0,-232,23,l.ink,574,185);u.text(this.panel,this.config.text.detail,0,-362,20,l.muted,575,40);u.button(this.panel,this.config.text.back,0,l.tabY,300,()=>{this.selected=null;this.render();},l.gold,66);}
}
module.exports={HandbookView};
