'use strict';
const c=require('./handbook-detail-config'),data=require('./expedition-data'),assets=require('./handbook-detail-assets');
/** 按中英文实际显示宽度分行，技能文案完整保留，不省略、不截断。 */
function wrap(text,font){const max=Math.floor((c.width-c.padding*2)/font)-c.wrapSafety;let line='',used=0;const lines=[];for(const ch of text){const n=ch.charCodeAt(0)<128?.55:1;if(ch==='\n'||used+n>max){lines.push(line);line='';used=0;}if(ch!=='\n'){line+=ch;used+=n;}}if(line)lines.push(line);return lines;}
/** 从原阶级配置只读生成属性对照，未通18章展示四阶上限。 */
function query(id,cleared=0){const original=data.heroes.find(h=>h.id===id),hero=original&&{...original,tiers:original.tiers.map(require("./skill-timing").tier)};if(!hero)throw Error('未找到武将属性');const max=cleared>=c.fiveStarChapter?5:c.normalMax,tiers=hero.tiers.filter(t=>t.star>=hero.tier&&t.star<=max),low=tiers[0],high=tiers.at(-1);return {hero,cards:(low.star===high.star?[high]:[low,high]).map(t=>({...t,max:t===high,primary:assets.primary[t.sourceId]??0}))};}
/** 优先使用大字，根据完整技能长度计算单页高度，长描述只在必要时小幅调整字号。 */
function layout(tier){let result;for(let font=c.font;font>=c.minFont;font--){let height=c.header;const rows=tier.skills.map(s=>{const lines=wrap(s.description,font),row={...s,lines,top:height,height:c.skillHeader+lines.length*font*c.lineRatio+c.skillGap};height+=row.height;return row;});result={font,rows,height:Math.max(c.minHeight,height+c.bottom)};if(result.height<=c.maxHeight)return result;}return result;}
/** 左对齐文本，名称、冷却和技能说明沿同一基线排列。 */
function text(host,parent,value,x,y,size,width,height,color=c.ink){const label=host.ui.text(parent,value,x,y,size,color,width,height);label.horizontalAlign=host.cc.Label.HorizontalAlign.LEFT;label.enableWrapText=false;label.lineHeight=size+2;return label;}
/** 弹出最低阶与最高阶对照；关闭只返回原图鉴，不触发招募、合成或存档写入。 */
function show(book,id){const host=book.host,u=host.ui,cc=host.cc,{hero,cards}=query(id,host.progress.state.cleared),shade=u.box(book.modal,'handbook-detail-overlay',0,0,720,1280,'#15120F99',false);shade.addComponent(cc.BlockInputEvents);cards.forEach((tier,i)=>{const p=layout(tier),x=(i-(cards.length-1)/2)*(c.width+c.gap),card=host.paper(shade,'handbook-tier-'+tier.star,x,0,c.width,p.height),top=p.height/2;card.addComponent(cc.BlockInputEvents);u.box(card,'prime',-c.width/2+29,top-28,43,43,c.primaryColors[tier.primary]);u.text(card,c.primary[tier.primary],-c.width/2+29,top-28,31,'#FFFFFF',40,40);u.box(card,'grade',-62,top-c.titleInset,42,42,c.rankColors[tier.star-1]);u.text(card,tier.star,-62,top-c.titleInset,30,'#FFFFFF',40,40);u.text(card,hero.name,42,top-c.titleInset,31,c.rankColors[tier.star-1],155,45);const actor=u.actor(card,{uid:i+1,heroId:id,star:tier.star},0,top-c.actorInset,c.actorScale,false);u.face(actor,0,-1);if(tier.max)u.text(card,'Max',0,top-c.maxInset,22,'#E1B51F',100,26);[hero.faction,hero.role,String(tier.range)].forEach((name,j)=>{const px=(j-1)*105;u.box(card,'trait-'+j,px,top-c.traitsInset+15,52,45,j===0?'#4B7645':j===1?'#A17227':'#835638');u.text(card,name,px,top-c.traitsInset+15,j===1?22:26,'#FFF1D4',68,42);u.text(card,['阵营','职业','射程'][j],px,top-c.traitsInset-25,23,c.ink,95,35);});text(host,card,'♥ '+tier.hp,-70,top-c.statsInset,24,145,35,'#98392B');text(host,card,'⚔ '+tier.attack,86,top-c.statsInset,24,145,35);text(host,card,'物防 '+tier.armor,-70,top-c.statsInset-43,24,145,35);text(host,card,'魔防 '+tier.magicArmor,86,top-c.statsInset-43,24,145,35);u.text(card,'—— 技能 ——',0,top-c.skillInset,25,c.ink,c.width-20,40);for(const row of p.rows){const y=top-row.top;const icon=assets.icons[row.id];if(icon)u.image(card,icon,-c.width/2+c.padding+c.iconSize/2,y-c.iconSize/2,c.iconSize,c.iconSize);text(host,card,row.name,-c.width/2+c.padding+c.iconSize+8+110,y-13,26,220,30);text(host,card,row.cooldown?'冷却时间：'+row.cooldown+'秒':'被动',-c.width/2+c.padding+c.iconSize+8+110,y-39,22,220,30);const height=row.lines.length*p.font*c.lineRatio;const label=text(host,card,row.lines.join('\n'),0,y-c.skillHeader-height/2,p.font,c.width-c.padding*2,height);label.lineHeight=p.font*c.lineRatio;}});u.text(shade,'点击空白处返回图鉴',0,c.closeY,26,'#FFFFFF',650,40);shade.on(cc.Node.EventType.TOUCH_END,e=>{e.propagationStopped=true;if(e.target===shade)shade.destroy();});}
module.exports={query,layout,wrap,show};
