'use strict';
const config=require('./hero-skill-config'),{distance}=require('./combat');
/** 只查询本阶已解锁技能，以稳定 ID 绑定规则。 */
function entries(a){return (a.skills||[]).map(s=>({...s,rule:config[s.id]})).filter(s=>s.rule);}
/** 根据技能种类读取单项被动。 */
function passive(a,kind){return entries(a).find(s=>s.rule.kind===kind)?.rule;}
/** 前两章完整技能走独立调度，其他武将暂保留旧主技能实现。 */
function managed(a){return config.supportHeroes.includes(a.heroId);}
/** 统一发送技能表现元数据，事件与真实结算共享技能 ID。 */
function emit(events,a,target,skill,t){events.push({type:'ability',t,uid:a.uid,target:target.uid,effect:skill.rule.effect,skillId:skill.id,skillName:skill.name,duration:skill.rule.duration||0});}
/** 辉煌和强击不重复叠加；初始化主动技能独立冷却和基础被动。 */
function initialize(units,events=[]){for(const a of units){a.cooldownFactor=1;a.buffs={};a.baseAttack=a.attack;for(const caster of units.filter(u=>u.side===a.side)){const aura=passive(caster,'aura');if(aura)a.cooldownFactor=Math.min(a.cooldownFactor,1-(a===caster?aura.selfReduction:aura.allyReduction));}a.skillTimers=Object.fromEntries(entries(a).filter(s=>config.activeKinds.includes(s.rule.kind)).map(s=>[s.id,(s.rule.initialCooldown??s.cooldown)*a.cooldownFactor]));a.nextSkill*=a.cooldownFactor;const shield=passive(a,'reduction');if(shield)a.reduction=1-(1-a.reduction)*(1-shield.reduction);const aim=passive(a,'aim');if(aim){a.range=aim.range;a.interval/=1+aim.haste;}}for(const a of units){const bonus=Math.max(0,...units.filter(u=>u.side===a.side).map(u=>(passive(u,'attackAura')?.power||0)*u.baseAttack));a.attack+=bonus;}for(const a of units)for(const skill of entries(a)){if(['aura','attackAura','reduction','aim','slowAura','rot'].includes(skill.rule.kind))events.push({type:'status',t:0,target:a.uid,effect:skill.rule.kind,skillId:skill.id,duration:0});}}
/** 临时增益覆盖同名旧增益，到期统一撤销，避免重复叠加数值漂移。 */
function buff(a,key,values,until){a.buffs=a.buffs||{};const old=a.buffs[key];if(old)for(const [k,v]of Object.entries(old.values))a[k]-=v;for(const [k,v]of Object.entries(values))a[k]=(a[k]||0)+v;a.buffs[key]={values,until};}
/** 每帧清除到期增益，持续被动通过同一命中队列结算。 */
function tick(a,units,t,hits,events){for(const [key,b]of Object.entries(a.buffs||{}))if(b.until<=t){for(const [k,v]of Object.entries(b.values))a[k]-=v;delete a.buffs[key];}if(a.hp<=0)return;if(a.channelUntil>t&&(a.stunnedUntil>t||a.silencedUntil>t)){a.channelUntil=t;a.channelInterruptedAt=t;}const rot=passive(a,'rot');if(rot&&(a.nextRot||rot.period)<=t){a.nextRot=t+rot.period;for(const u of units.filter(u=>u.side!==a.side&&u.hp>0&&distance(a,u)<=rot.radius))hits.push({at:t,a,u,power:rot.power,skill:true,critical:false,effect:rot.effect,s:{}});}a.auraSlow=Math.max(0,...units.filter(u=>u.side!==a.side&&u.hp>0).map(u=>{const s=passive(u,'slowAura');return s&&distance(a,u)<=s.radius?s.slow:0;}));}
/** 查询普通攻击附带的既有被动，不把火箭误标成主动技能。 */
function attackSpec(a,rng){for(const kind of ['bonus','slowAttack','delay','bash']){const s=passive(a,kind);if(!s)continue;if(kind==='bash'&&rng()>=s.chance)return {};return {...s,passive:kind==='slowAttack'?'slow':kind};}return {};}
/** 决定技能的实际目标，嘲讽仅影响普攻选敌。 */
function select(a,targets,s,rng){if(s.select==='random')return targets[Math.floor(rng()*targets.length)];if(s.select==='highestAttack')return [...targets].sort((x,y)=>y.attack-x.attack||x.uid-y.uid)[0];if(s.select==='lowest')return [...targets].sort((x,y)=>x.hp-y.hp||x.uid-y.uid)[0];if(s.select==='farthest')return targets[targets.length-1];return targets[0];}
/** 找到目标周围空格，避免钩取、闪烁与已有单位重叠。 */
function freeNear(target,units,rules,radius=config.defaults.nearRadius){const free=[];for(let y=Math.max(0,target.y-radius);y<=Math.min(rules.rows*2-1,target.y+radius);y++)for(let x=Math.max(0,target.x-radius);x<=Math.min(rules.columns-1,target.x+radius);x++)if(!units.some(u=>u.hp>0&&u.x===x&&u.y===y))free.push({x,y});return free;}
/** 一次实际施法同时安排伤害、控制和增益，多重施法只重复有效技能。 */
function cast(a,target,skill,units,t,hits,events,heal,rules,rng){const s=skill.rule,allies=units.filter(u=>u.side===a.side&&u.hp>0),enemies=units.filter(u=>u.side!==a.side&&u.hp>0);emit(events,a,target,skill,t);events[events.length-1].impactDelay=s.windup||rules.attackDelay;const soul=passive(a,'flameSoul');if(soul){buff(a,'flameSoul',{skillHaste:soul.haste,attack:a.baseAttack*soul.attack},t+soul.duration);events.push({type:'status',t,target:a.uid,effect:'flameSoul',duration:soul.duration});}
 if(s.kind==='haste'||s.kind==='allyHaste'){const u=s.kind==='haste'?a:allies[Math.floor(rng()*allies.length)];buff(u,'haste',{skillHaste:s.haste},t+s.duration);events.push({type:'status',t,target:u.uid,effect:s.effect,duration:s.duration});return;}
 if(s.kind==='pact'){heal(a,a.maxHp*s.heal,t);a.attack+=a.baseAttack*s.attack;return;}
 if(s.kind==='heal'){for(const u of allies)heal(u,a.attack*s.power,t);return;}
 if(s.kind==='cleanse'){const u=allies.find(u=>u.stunnedUntil>t||u.silencedUntil>t||u.slowUntil>t||u.tauntUntil>t);if(u){u.stunnedUntil=0;u.slowUntil=0;u.silencedUntil=0;u.tauntUntil=0;buff(u,'cleanse',{magicArmor:s.magicArmor},t+s.duration);events.push({type:'status',t,target:u.uid,effect:'cleanse',duration:s.duration});}return;}
 if(s.kind==='protect'){for(const u of allies){buff(u,'protect',{armor:s.armor},t+s.duration);for(let n=s.period;n<=s.duration;n+=s.period)hits.push({at:t+n,a,u,healPower:s.power,skill:true,s:{}});events.push({type:'status',t,target:u.uid,effect:s.effect,duration:s.duration});}return;}
 if(s.kind==='enrage'){buff(a,'enrage',{attack:a.maxHp*s.hpAttack,reduction:s.reduction},t+s.duration);events.push({type:'status',t,target:a.uid,effect:s.effect,duration:s.duration});return;}
 if(s.kind==='taunt'){buff(a,'taunt',{armor:s.armor,magicArmor:s.magicArmor},t+s.duration);for(const u of enemies.filter(u=>distance(a,u)<=s.radius)){if(require('./talent-effects').resists(u,rng))continue;u.tauntUid=a.uid;u.tauntUntil=t+s.duration;events.push({type:'status',t,target:u.uid,effect:s.effect,duration:s.duration});}return;}
 if(s.kind==='blinkStrike'){const p=freeNear(target,units,rules)[0];if(p){Object.assign(a,p);events.push({type:'move',t,uid:a.uid,...p,duration:rules.tickSeconds,effect:s.effect});}}
 const affected=s.line?enemies.filter(u=>u.x===target.x||u.y===target.y):s.radius===undefined?[target]:enemies.filter(u=>distance(u,s.selfCenter?a:target)<=s.radius);
 if(s.kind==='silence'){for(const u of affected){if(require('./talent-effects').resists(u,rng))continue;u.silencedUntil=t+s.duration;events.push({type:'status',t,target:u.uid,effect:s.effect,duration:s.duration});}return;}
 if(s.kind==='freeze'&&!require('./talent-effects').resists(target,rng)){target.stunnedUntil=Math.max(target.stunnedUntil,t+s.duration);events.push({type:'status',t,target:target.uid,effect:s.effect,duration:s.duration});}
 if(s.kind==='channel')a.channelUntil=t+s.duration;
 const periodic=['dot','freeze','channel'].includes(s.kind),count=periodic?Math.round(s.duration/s.period):s.count||1;
 for(let n=0;n<count;n++)for(const u of (s.kind==='execute'?[target]:affected))hits.push({at:t+(periodic?(n+1)*s.period:(s.windup||rules.attackDelay)+n*(s.period||0)),a,u,power:s.power,skill:true,critical:false,effect:s.effect,skillId:skill.id,execute:s.kind==='execute',channel:s.kind==='channel'||!!s.windup,channelStart:t,s:{...s,duration:periodic?s.period:s.duration}});
 if(s.windup)a.channelUntil=t+s.windup;}
/** 冷却按技能独立推进；被沉默时仍可普攻，持续施法占用行动直到结束。 */
function activate(a,target,units,t,hits,events,heal,rules,rng){if(a.silencedUntil>t)return false;const targets=units.filter(u=>u.hp>0&&u.side!==a.side).sort((x,y)=>distance(a,x)-distance(a,y)||x.uid-y.uid);const skill=entries(a).find(s=>config.activeKinds.includes(s.rule.kind)&&a.skillTimers[s.id]<=t&&(s.rule.global||targets.some(u=>distance(a,u)<=a.range))&&(s.rule.kind!=='cleanse'||units.some(u=>u.side===a.side&&u.hp>0&&(u.stunnedUntil>t||u.silencedUntil>t||u.slowUntil>t||u.tauntUntil>t))));if(!skill)return false;const s=skill.rule;a.skillTimers[skill.id]=t+skill.cooldown*a.cooldownFactor;target=select(a,s.global?targets:targets.filter(u=>distance(a,u)<=a.range),s,rng);const multi=passive(a,'multicast');let count=1;if(multi){let r=rng();for(const c of multi.chances){if(r<c.chance){count=c.count;break;}r-=c.chance;}}if(count>1)events.push({type:'ability',t,uid:a.uid,target:a.uid,effect:'multicast',count,skillId:entries(a).find(x=>x.rule.kind==='multicast').id});for(let i=0;i<count;i++)cast(a,target,skill,units,t,hits,events,heal,rules,rng);a.nextAction=t+(s.kind==='channel'?s.duration:s.windup||a.interval/(1+(a.skillHaste||0)));return true;}
/** 普攻附加撕裂并在三次攻击后闪避移位；事件只对真实触发发出。 */
function afterAttack(a,units,t,events,rng,rules){const skill=entries(a).find(s=>s.rule.kind==='blink');if(!skill||a.attacks%skill.rule.every)return;const s=skill.rule,free=freeNear(a,units,rules,s.radius);a.dodgeUntil=t+s.duration;a.skillDodge=s.dodge;if(free.length){Object.assign(a,free[Math.floor(rng()*free.length)]);events.push({type:'move',t,uid:a.uid,x:a.x,y:a.y,duration:rules.tickSeconds});}emit(events,a,a,skill,t);}
/** 命中后的撕裂按来源独立计时；斩杀成功只刷新该技能。 */
function onHit(a,u,hit,t,events=[]){if(hit.execute&&u.hp<=0)a.skillTimers[hit.skillId]=t;if(hit.skill)return;const s=passive(a,'rend');if(s){u.rends=u.rends||{};const old=u.rends[a.uid];u.rends[a.uid]={value:(old?.until>t?old.value:0)+a.attack*s.power,until:t+s.duration};events.push({type:'status',t,target:u.uid,effect:'rend',duration:s.duration,stacks:Math.round(u.rends[a.uid].value/(a.attack*s.power))});}}
/** 单位死亡统一触发吞噬与肢解，伤害排队避免递归重入。 */
function onDeath(dead,units,t,hits,heal,events){for(const a of units.filter(u=>u.hp>0)){const s=passive(a,'consume');if(s&&!dead.summoned){heal(a,dead.maxHp*s.heal,t);events.push({type:'status',t,target:a.uid,effect:s.effect,duration:.7});}}const s=passive(dead,'deathBlast');if(s)for(const u of units.filter(u=>u.side!==dead.side&&u.hp>0&&distance(dead,u)<=s.radius))hits.push({at:t,a:dead,u,flatDamage:dead.maxHp*s.power,skill:true,effect:s.effect,s});}
module.exports={buff,entries,passive,managed,initialize,tick,attackSpec,activate,afterAttack,onHit,onDeath};
