"use strict";
const c=require('./combat-feedback-config').banner;
/** 清除上一次横幅及动画，避免连续击杀堆叠遮挡棋盘。 */
function clear(v){const n=v.killBanner;if(n?.isValid){v.cc.Tween.stopAllByTarget(n);const o=n.getComponent(v.cc.UIOpacity);if(o)v.cc.Tween.stopAllByTarget(o);n.destroy();}v.killBanner=null;}
/** 使用原版金色横幅、击杀图案和双方武将头像播放弹入淡出动画。 */
function show(v,info){if(!info)return;const key=info.key||(info.count===1?'first':String(Math.min(info.count,c.maxCount))),entry=require('./announcer-config')[key];if(!entry||entry.banner===false)return;clear(v);const u=v.ui,cc=v.cc,n=u.node(v.root,'kill-banner',0,c.y);v.killBanner=n;u.image(n,'feedback/background.png',0,0,c.width,c.height);for(const [unit,x,frame]of (info.killer&&info.victim?[[info.killer,-c.portraitX,'attacker'],[info.victim,c.portraitX,'victim']]:[])){const p=u.node(n,'kill-portrait',x,0,c.portraitSize,c.portraitSize);p.addComponent(cc.Mask).type=cc.Mask.Type.ELLIPSE;u.image(p,unit.heroId+'-avatar.png',0,0,c.portraitSize,c.portraitSize);u.image(n,'feedback/'+frame+'.png',x,0,c.frameSize,c.frameSize);}const style=c.textStyle;if(entry.image)u.image(n,entry.image,0,style.titleY,c.textWidth,style.titleHeight);else{const font=Math.min(style.font,c.textWidth/(entry.title.length*style.asciiWidth)),label=u.text(n,entry.title,0,style.titleY,font,style.color,c.textWidth,style.titleHeight);label.isBold=true;label.fontFamily=style.fontFamily;label.enableWrapText=false;const outline=label.node.addComponent(cc.LabelOutline);outline.color=new cc.Color(style.outline);outline.width=style.outlineWidth;}u.text(n,entry.image?entry.title:entry.subtitle,0,style.subtitleY,style.subtitleFont,style.color,c.textWidth,style.subtitleHeight);n.setScale(.25,.25,1);const opacity=n.addComponent(cc.UIOpacity);cc.tween(n).to(c.enter,{scale:new cc.Vec3(1.08,1.08,1)}).to(c.settle,{scale:new cc.Vec3(1,1,1)}).start();cc.tween(opacity).delay(c.enter+c.settle+c.hold).to(c.fade,{opacity:0}).call(()=>{if(n.isValid)n.destroy();if(v.killBanner===n)v.killBanner=null;}).start();}
/** 备战期间预载小型横幅图片，首次击杀不等待解码。 */
function warm(v){const files=new Set(['feedback/background.png','feedback/attacker.png','feedback/victim.png',...Object.values(require('./announcer-config')).map(entry=>entry.image).filter(Boolean)]);for(const file of files)v.assets.sprite(file).catch(()=>{});}
module.exports={show,clear,warm};
