'use strict';
const manifest=require('./native-effect-manifest.js'),config=require('./native-effect-config');
/** 每张图集只装配一次帧对象，与图片缓存共用生命周期。 */
function frames(v,id){v.nativeFrames=v.nativeFrames||new Map();if(!v.nativeFrames.has(id)){const m=manifest[id];v.nativeFrames.set(id,v.assets.texture(m.file).then(texture=>Array.from({length:m.count},(_,i)=>{const f=new v.cc.SpriteFrame();f.texture=texture;f.rect=new v.cc.Rect(i%m.columns*m.size,Math.floor(i/m.columns)*m.size,m.size,m.size);f.originalSize=new v.cc.Size(m.size,m.size);f.offset=new v.cc.Vec2(0,0);f.addRef();return f;})).catch(e=>{v.nativeFrames.delete(id);throw e;}));}return v.nativeFrames.get(id);}
/** 备战阶段预热原生特效，避免首次技能触发时才解码贴图。 */
function warm(v){return Promise.all(Object.keys(manifest).map(id=>frames(v,id))).catch(e=>console.warn('原生特效预热失败',e.message));}
/** 清理唯一帧循环和节点，保留已经装配的共享图集。 */
function clear(v){clearInterval(v.nativeTimer);v.nativeTimer=null;for(const e of v.nativeEffects||[])if(e.node.isValid)e.node.destroy();v.nativeEffects=[];}
/** 使用真实帧序列播放粒子和拖尾，循环状态在死亡、驱散、离场时结束。 */
function play(v,id,parent,x,y,{duration=0,size=config.sizes[id]||config.defaultSize,loop=false,travel=null,angle=0,spin=0,follow=null,delay=0,color=null,widthRatio=1,heightRatio=1,fadeOut=0,followTarget=null,targetOffsetY=0}={}){if(!manifest[id])return null;v.nativeEffects=(v.nativeEffects||[]).filter(e=>e.node.isValid);while(v.nativeEffects.length>=config.maxNodes){const i=Math.max(0,v.nativeEffects.findIndex(e=>!e.loop));const e=v.nativeEffects.splice(i,1)[0];e.node.destroy();}const n=v.ui.node(parent,'native-effect-'+id,x,y,size,size),sp=n.addComponent(v.cc.Sprite);sp.sizeMode=v.cc.Sprite.SizeMode.CUSTOM;n.angle=angle;n.setScale(widthRatio,heightRatio,1);if(color)sp.color=new v.cc.Color(color);n.active=delay<=0;const m=manifest[id],e={node:n,sp,id,loop,travel,follow,angle,spin,x,y,start:null,duration:duration||m.count/m.fps,frames:null,fadeOut,followTarget,targetOffsetY,opacity:fadeOut>0?n.addComponent(v.cc.UIOpacity):null};v.nativeEffects.push(e);frames(v,id).then(f=>{if(n.isValid){e.frames=f;e.start=Date.now();e.last=e.start;e.elapsed=-Math.max(0,delay);sp.spriteFrame=f[0];}}).catch(err=>{if(n.isValid)n.destroy();console.warn('原生特效加载失败',id,err.message);});if(!v.nativeTimer)v.nativeTimer=setInterval(()=>tick(v),config.frameInterval);return n;}
/** 单一计时器推进所有效果，动画与战斗倍速同步，不改变命中时刻。 */
function tick(v){const now=Date.now();for(const e of v.nativeEffects||[]){if(!e.node.isValid)continue;if((e.follow&&!e.follow.isValid)||(e.followTarget&&!e.followTarget.isValid)){e.node.destroy();continue;}if(e.start===null)continue;const elapsed=(e.elapsed||0)+(now-(e.last??e.start))/1000*v.speed;e.elapsed=elapsed;e.last=now;if(elapsed<0)continue;e.node.active=true;if(elapsed>=e.duration){e.node.destroy();continue;}if(e.opacity)e.opacity.opacity=Math.round(255*Math.min(1,(e.duration-elapsed)/(e.duration*e.fadeOut)));if(e.frames){const m=manifest[e.id],index=e.loop?Math.floor(elapsed*m.fps)%m.count:Math.min(m.count-1,Math.floor(elapsed/e.duration*m.count));e.sp.spriteFrame=e.frames[index];}if(e.follow)e.node.setPosition(e.follow.position.x+e.x,e.follow.position.y+e.y);if(e.spin)e.node.angle=e.angle+e.spin*elapsed/e.duration;if(e.travel){const t=elapsed/e.duration,q=e.followTarget?{x:e.followTarget.position.x,y:e.followTarget.position.y+e.targetOffsetY}:e.travel;e.node.setPosition(e.x+(q.x-e.x)*t,e.y+(q.y-e.y)*t);if(e.followTarget)e.node.angle=Math.atan2(q.y-e.y,q.x-e.x)*180/Math.PI;}}v.nativeEffects=(v.nativeEffects||[]).filter(e=>e.node.isValid);if(!v.nativeEffects.length){clearInterval(v.nativeTimer);v.nativeTimer=null;}}
module.exports={warm,clear,play,tick,frames};
