'use strict';
const c=require('./revive-config'),service=require('./revive');
/** 最后一命复活使用保存的截止时间，广告期间暂停，取消后接续剩余倒计时。 */
function show(v,p){const deadline=service.open(v.model,p.id),u=v.ui,m=v.overlay(),lord=v.progress.lord();const l=c.layout;u.box(m,'revive-panel',0,l.panelY,l.panelWidth,l.panelHeight,'#10333DEF',false);u.text(m,c.title,0,l.titleY,58,'#92CAFF',580,78);const avatar=u.node(m,'revive-portrait',l.portraitX,l.portraitY,l.portraitWidth,l.portraitHeight);avatar.addComponent(v.cc.Mask).type=v.cc.Mask.Type.ELLIPSE;u.portrait(avatar,lord.portrait,0,0,l.portraitWidth,l.portraitHeight,require('./classic-config').portraitCrop);u.box(m,'revive-level',l.portraitX,80,146,39,'#171F23',false);u.text(m,'等级 '+v.model.state.expedition.level,l.portraitX,80,27,'#FFFFFF',140,38);u.text(m,'♡'.repeat(lord.hp),l.portraitX,37,32,'#729399',175,43);v.paper(m,'revive-speech',l.textX,l.textY,418,170);u.text(m,c.advice,l.textX,l.textY,35,l.ink,365,135);u.text(m,'天赋树加点 ✚，大幅提升实力！',0,l.hintY-25,30,'#FF6860',650,48);const ring=u.node(m,'revive-count-ring',0,c.countY),g=ring.addComponent(v.cc.Graphics);const count=u.text(m,'10',0,c.countY,c.countFont,'#FFDB9F',180,100);u.text(m,'额外获得2级武将',170,l.rewardY,26,'#FFFFFF',320,38);v.paper(m,'revive-guide-speech',70,l.footerY,495,140);u.image(m,'zhenji-avatar.png',-246,l.footerY+25,138,154);u.text(m,c.guide,70,l.footerY,30,l.ink,420,100);require('./revive-voice').play(v,m,p);let timer=null,busy=false;
 /** 停止旧计时后一次性结算并转入远征结算页。 */
 const surrender=()=>{if(busy)return;busy=true;clearInterval(timer);v.act(()=>{service.surrender(v.model,p.id);v.page='map';});};
 require('./benefit-ui').button(v,m,c.decline,-170,c.buttonY,290,surrender,'red');require('./benefit-ui').button(v,m,c.accept,170,c.buttonY,290,()=>{if(busy)return;try{service.pause(v.model,p.id);busy=true;clearInterval(timer);const ticket=v.model.adTicket();let receipt;v.ad(()=>{receipt=service.claim(v.model,p.id,ticket);},()=>require('./lord-blessing-view').show(v,receipt),()=>{service.open(v.model,p.id);v.render();});}catch(e){surrender();}},'gold');
 /** 依据绝对时间计时，切后台不会凭空多出十秒。 */
 const tick=()=>{if(!m.isValid){clearInterval(timer);return;}const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));count.string=String(left);g.clear();g.strokeColor=new v.cc.Color('#BFA985');g.lineWidth=c.ring.width;g.circle(0,0,c.ring.radius);g.stroke();g.strokeColor=new v.cc.Color(c.ring.color);g.arc(0,0,c.ring.radius,Math.PI/2,Math.PI/2+Math.PI*2*left/c.seconds,false);g.stroke();if(!left)surrender();};timer=setInterval(tick,c.tickMs);m.once(v.cc.Node.EventType.NODE_DESTROYED,()=>clearInterval(timer));tick();return m;}
module.exports={show};
