'use strict';
const presentation=require('./skill-presentation-config'),c=require('./native-effect-config'),native=require('./native-effects');
/** 在真实目标处播放原始模型的粒子动画，不再绘制几何替代效果。 */
function paint(v,target,key,source,duration){if(key==='equipment-'+require('./equipment-chain-config').id)return;if(key==='rot'&&source?.unit.heroId===require('./original-zhangfei-config').hero)return;if(!target?.node.isValid)return;const options=require('./hero-vfx').skillOptions(key,source,target);const id=options.id||presentation.impact[key]||c.impactMap[key]||c.map[key];if(!id)return;const p=target.node.position;return native.play(v,id,v.root,p.x,p.y+c.offsetY,{duration:duration||c.durations[key],size:c.impactSizes[key]||c.sizes[id]||c.defaultSize,spin:0,...options});}
/** 冰封使用原冻结模型，跟随目标并维持与控制相同的持续时间。 */
function freeze(v,target,duration){if(!target?.node.isValid)return;if(target.frozenEffect?.isValid)target.frozenEffect.destroy();target.frozenEffect=native.play(v,'freeze',v.root,0,c.freezeOffset,{duration,loop:true,follow:target.node});}
/** 火箭使用原 SearingArrow 模型动画及拖尾，沿真实目标方向飞行。 */
function arrow(v,a,b){const p=a.node.position,q=b.node.position;return native.play(v,a.unit.heroId==='taishici'?'fireArrow':a.unit.heroId==='xiahouyuan'?'coldArrow':'arrow',v.root,p.x,p.y+c.offsetY,{size:c.projectileSize,duration:v.config.attackDelay,angle:Math.atan2(q.y-p.y,q.x-p.x)*180/Math.PI,travel:{x:q.x,y:q.y+c.offsetY}});}
/** 施法与命中分别播放，伤害技能不在出手时提前显示命中特效。 */
function ability(v,a,target,e){if(require('./zhouyu-effects').ability(v,a,target,e))return;if(e.effect==='multicast'){require('./skill-status-view').announce(v,a,'多重施法 ×'+e.count);return;}if(e.effect==='hook'){if(require('./original-zhangfei-effects').hook(v,a,target,e.impactDelay*2))return;require('./skill-trajectories').hook(v,a,target,e.impactDelay*2);return;}if(e.effect==='volley'){const rule=require('./hero-skill-config')[e.skillId],p=a.node.position,q=target?.node.position;if(q)for(let i=0;i<rule.count;i++)native.play(v,'coldArrow',v.root,p.x,p.y+c.offsetY,{size:c.projectileSize,duration:e.impactDelay,delay:i*rule.period,angle:Math.atan2(q.y-p.y,q.x-p.x)*180/Math.PI,travel:{x:q.x,y:q.y+c.offsetY}});return;}if(e.effect==='snipe'){require('./skill-status-view').announce(v,a,'瞄准');return;}if(e.effect==='blizzard'){require('./blizzard-view').begin(v,a,target,e);return;}if(e.effect==='whirl'){require('./whirl-motion').play(v,a,c.durations.whirl);native.play(v,c.map.whirl,v.root,0,c.whirlOffsetY,{duration:c.durations.whirl,size:c.whirlSize,loop:true,follow:a.node});return;}if(c.castEffects.includes(e.effect))paint(v,c.selfEffects.includes(e.effect)?a:target||a,e.effect,a);}
/** 驱散立即移除冰封；其他持续状态由原特效图集呈现。 */
function status(v,target,e){if(e.effect==='hex')return require('./equipment-vfx').hex(v,target,e);if(e.effect==='rot'&&require('./original-zhangfei-effects').rot(v,target)){require('./skill-status-view').show(v,target,e);return;}require('./skill-status-view').show(v,target,e);if(e.effect==='rend'&&e.stacks>1)require('./skill-status-view').announce(v,target,'撕裂 ×'+e.stacks);if(presentation.persistent.includes(e.effect)&&e.effect!=='rot')return;if(e.effect==='freeze')return freeze(v,target,e.duration);if(e.effect==='cleanse'){if(target.frozenEffect?.isValid)target.frozenEffect.destroy();require('./skill-status-view').remove(v,target,['11011','11032']);}const id=presentation.states[e.effect]||c.map[e.effect]||require('./equipment-vfx-config').statuses[e.effect];if(!id)return;if(e.effect==='cleanse')return paint(v,target,e.effect);const key='status-'+e.effect;if(target[key]?.isValid)target[key].destroy();return target[key]=native.play(v,id,target.node,0,e.effect==='silence'?require('./equipment-vfx-config').silence.y:c.offsetY,{size:e.effect==='silence'?require('./equipment-vfx-config').silence.size:undefined,duration:presentation.flashStates.includes(e.effect)?presentation.status.flashSeconds:(e.duration||presentation.status.flashSeconds),loop:true});}
module.exports={paint,burst:paint,freeze,arrow,ability,status};
