'use strict';
const c=require('./sweep-config');
/** 奖励按钮使用红金区分普通和双倍，并阻断点击穿透。 */
function button(v,p,text,x,y,width,action,color){const n=v.ui.node(p,text,x,y,width,82);v.ui.image(n,'classic/button-'+color+'.png',0,0,width,82);require('./button-content').draw(v.ui,n,text,31,'#FFE369',width-16,72);n.on(v.cc.Node.EventType.TOUCH_END,e=>{e.propagationStopped=true;action();});return n;}
/** 统一通关与扫荡物品展示，碎片使用装备图标并标注实际入库数量。 */
function reward(v,items,normal,double){const m=v.overlay(),u=v.ui,g=u.node(m,'reward-ornament').addComponent(v.cc.Graphics);g.strokeColor=new v.cc.Color('#D6B574');g.lineWidth=2;for(const y of [155,-172]){g.moveTo(-305,y);g.lineTo(-35,y);g.moveTo(35,y);g.lineTo(305,y);g.moveTo(-32,y);g.lineTo(0,y+12);g.lineTo(32,y);g.lineTo(0,y-12);g.close();g.stroke();}u.text(m,'获得物品',0,220,58,'#FFE2A0',620,90);const entries=Object.entries(items).sort(([a],[b])=>c.order.indexOf(a)-c.order.indexOf(b));entries.forEach(([id,count],i)=>{const x=(i%c.columns-(c.columns-1)/2)*c.gap,y=c.top-Math.floor(i/c.columns)*c.rowGap,n=u.box(m,'sweep-item-'+id,x,y,c.icon+6,c.icon+6,id==='1'?'#A42C25':'#237BAE');u.image(n,id==='1'?'classic/diamond.png':id==='101'?'classic/item-101.png':'equipment/'+id+'.png',0,0,c.icon,c.icon);if(id!=='1')u.text(n,'碎片',0,27,18,'#FFD269',c.icon,30);u.text(n,id==='1'?require('./vip').diamonds(v.model,count):count,15,-25,28,'#FFFFFF',c.icon,40);});button(v,m,'▶ 双倍领取',-162,c.rewardButtonY,294,double,'gold');button(v,m,'确定',162,c.rewardButtonY,294,normal,'red');return m;}
/** 通关后显示十次额度，前三次免费，剩余次数只接完整视频回调。 */
function home(v){const s=require('./sweep').status(v.progress);if(!s.unlocked||v.model.state.pending)return;button(v,v.root,s.remaining?(s.free?'免费扫荡':'▶ 扫荡'):'今日已扫荡',0,c.buttonY,c.buttonWidth,()=>{if(!s.remaining)return;const service=require('./sweep');if(service.status(v.progress).free)v.act(()=>service.begin(v.progress));else{const ticket=service.ticket(v.progress);v.ad(()=>service.begin(v.progress,ticket));}},s.free?'red':'gold');v.ui.text(v.root,'今日剩余 '+s.remaining+' 次',0,c.countY,28,'#FFFFFF',430,48);}
/** 待领取扫荡快照可从任意主页标签恢复，普通与双倍只能选一次。 */
function show(v){const r=v.progress.state.sweep?.pending;if(!r)return;const service=require('./sweep'),ticket=v.model.adTicket();reward(v,r.items,()=>v.act(()=>service.claim(v.progress,r.id)),()=>v.ad(()=>service.claim(v.progress,r.id,ticket)));}
module.exports={home,show,reward};
