'use strict';
const c=require('./tutorial-config');
/** 根据真实合成与部署结果切换教学，重绘或重启不会重复发放资源。 */
function step(m){const s=m.state,p=s.meta;if(!p||p.chapter!==1||p.section!==1||p.layer!==0||!p.activeNode||s.pending||s.battles>0||s.units.length>3)return null;const group=s.units.find(u=>s.units.filter(x=>x.heroId===u.heroId&&x.star===u.star).length>=m.rules.mergeCount);if(group)return {kind:'merge',unit:group};const bench=s.units.find(u=>u.slot<0);if(!s.units.some(u=>u.slot>=0)&&bench)return {kind:'deploy',unit:bench};return s.units.some(u=>u.slot>=0)?{kind:'start'}:null;}
/** 页面切换时终止手势循环，不保留对已销毁节点的引用。 */
function cancel(v){for(const n of v.guideTargets||[])v.cc.Tween.stopAllByTarget(n);v.guideTargets=[];}
/** 绘制白色指示手，指尖随脉冲或拖动轨迹循环。 */
function hand(v,parent,x,y){const n=v.ui.node(parent,'guide-hand',x,y),g=n.addComponent(v.cc.Graphics);g.fillColor=new v.cc.Color('#FFFDF4');g.strokeColor=new v.cc.Color('#3D4854');g.lineWidth=4;g.moveTo(-15,-22);g.lineTo(-30,-3);g.quadraticCurveTo(-35,9,-24,8);g.lineTo(-13,-1);g.lineTo(-13,36);g.quadraticCurveTo(-12,49,-2,42);g.lineTo(0,13);g.quadraticCurveTo(28,20,30,-3);g.lineTo(21,-28);g.close();g.fill();g.stroke();n.setScale(c.handScale,c.handScale,1);return n;}
/** 教学手势与拖动推荐共用站位查询，优先选择推荐行的中央空位。 */
function target(model,unit){const cells=require('./deployment-view').query(model,unit).filter(p=>p.recommended);return cells.sort((a,b)=>Math.abs(a.slot%model.rules.columns-c.recommendColumn)-Math.abs(b.slot%model.rules.columns-c.recommendColumn))[0]?.slot;}
/** 甄姬播放自身待机动作，推荐格与指示手循环；装饰不拦截武将触摸。 */
function show(v){if(!step(v.model)&&require("./equipment-tutorial-view").show(v))return;const s=step(v.model);if(!s||v.playing){require('./tutorial-voice').stop(v);return;}require('./tutorial-voice').play(v,s.kind);cancel(v);const u=v.ui,cc=v.cc,root=u.node(v.root,'new-player-guide'),y=c[s.kind+'Y'];if(s.kind==='merge'){u.box(root,'guide-dim-top',0,c.dim.topY,v.config.layout.width,c.dim.topHeight,c.dim.color,false);u.box(root,'guide-dim-bottom',0,c.dim.bottomY,v.config.layout.width,c.dim.bottomHeight,c.dim.color,false);}const panel=u.box(root,'guide-dialogue',c.boxX,y,c.boxWidth,c.boxHeight,'#E8CDA0');u.text(panel,c.text[s.kind],30,0,c.font,'#52351F',c.boxWidth-110,c.boxHeight-15);u.actor(root,{uid:-9999,heroId:c.hero,star:1,side:'enemy'},c.npcX,y+c.npcOffset,c.npcScale,false);let from,to;const bench=v.model.state.units.filter(x=>x.slot<0),i=bench.findIndex(x=>x.uid===s.unit?.uid);from={x:(i-(v.config.layout.benchPageSize-1)/2)*v.config.layout.benchSpacing,y:v.config.layout.benchY+c.handOffset};if(s.kind==='start')from={x:229,y:-585};if(s.kind==='deploy'){const slot=target(v.model,s.unit);if(slot===undefined)return;to=v.position(slot%v.config.columns,Math.floor(slot/v.config.columns));const glow=u.box(root,'recommended-cell',to.x,to.y,v.config.layout.boardHitWidth-8,v.config.layout.boardHitHeight-8,'#9DED4B55');const opacity=glow.addComponent(cc.UIOpacity);cc.tween(opacity).repeatForever(cc.tween().to(c.pulseSeconds,{opacity:90}).to(c.pulseSeconds,{opacity:255})).start();v.guideTargets.push(opacity);}const h=hand(v,root,from.x,from.y);v.guideTargets.push(h);if(to)cc.tween(h).repeatForever(cc.tween().to(c.dragSeconds,{position:new cc.Vec3(to.x,to.y+c.handOffset,0)}).delay(.3).set({position:new cc.Vec3(from.x,from.y,0)}).delay(.3)).start();else cc.tween(h).repeatForever(cc.tween().by(c.pulseSeconds,{position:new cc.Vec3(0,16,0)}).by(c.pulseSeconds,{position:new cc.Vec3(0,-16,0)})).start();}
module.exports={step,show,cancel,hand,target};
