'use strict';
const {Widgets}=require('./widgets');
class PlayView{
 /** 注入模型与引擎；视图不直接写存档，也不重新计算战斗。 */
 constructor(cc,root,assets,model,config,roster){Object.assign(this,{cc,root,assets,model,config,roster});this.ui=new Widgets(cc,assets,config.colors);this.page='home';this.selected=null;this.benchPage=0;this.speed=1;this.playing=false;this.timer=null;this.actors=new Map();this.message='拖动武将布阵，三名同阶武将可合成';this.render();}
 /** 执行领域操作并显示失败原因，战斗期间禁止变更阵容。 */
 act(operation){try{if(this.playing)throw Error('交战中，请等待结算或跳过动画');operation();}catch(error){this.message=error.message;}this.render();}
 /** 用原版六列透视网格的结构计算角色显示位置。 */
 position(x,y){return {x:(x-(this.config.columns-1)/2)*this.config.layout.boardX[y],y:this.config.layout.boardY[y]};}
 /** 将触点转换到己方格子；敌方或界外坐标不能布阵。 */
 slotAt(point){for(let y=0;y<this.config.rows;y++)for(let x=0;x<this.config.columns;x++){const p=this.position(x,y);if(Math.abs(p.x-point.x)<this.config.layout.boardX[y]/2&&Math.abs(p.y-point.y)<this.config.layout.boardHitHeight/2)return y*this.config.columns+x;}return null;}
 /** 当前章名和关卡号由配置映射，不绑定业务常量。 */
 chapter(){const r=this.config,s=this.model.state.stage;return r.chapterNames[Math.floor((s-1)/r.stagesPerChapter)%r.chapterNames.length]+' · 第 '+((s-1)%r.stagesPerChapter+1)+' 战';}
 /** 清理旧控件并按当前页面创建新视图，战斗过程另用增量更新。 */
 render(){if(this.playing)return;for(const child of [...this.root.children]){child.removeFromParent();child.destroy();}this.actors.clear();this.modal=null;this.ui.box(this.root,'base',0,0,720,1280,this.config.colors.ink,false);if(this.page==='battle'){this.renderBattle();return;}this.renderHeader();if(this.page==='home')this.renderHome();else if(this.page==='heroes')this.renderHeroes();else if(this.page==='camp')this.renderCamp();else if(this.page==='training')this.renderTraining();else this.renderRules();this.renderTabs();}
 /** 主界面保留顶部主将和资源区域。 */
 renderHeader(){const u=this.ui,c=this.config.colors;u.box(this.root,'header',0,566,700,120,c.panel);u.image(this.root,this.config.leaderHero+'-avatar.png',-274,570,100,100);u.text(this.root,this.config.title,20,589,32,c.gold,410);u.text(this.root,'军资 '+this.model.state.gold+'  ·  已胜 '+this.model.state.wins+' 场',25,543,23);}
 /** 用同一幅行军图承载本地关卡进度和出征入口。 */
 renderHome(){const u=this.ui,c=this.config.colors;u.image(this.root,this.config.mapImage,0,-10,720,1000);u.box(this.root,'chapter',0,422,500,65,c.panel);u.text(this.root,this.chapter(),0,422,32,c.paper,490);u.box(this.root,'campaign-marker',0,110,320,260,c.panel);u.text(this.root,'征',0,165,90,c.gold);u.text(this.root,'自由布阵 · 自动交战',0,80,24);u.button(this.root,this.model.state.pending?'查看待领取战果':'整军出征',0,-25,300,()=>{this.page='battle';this.render();});u.text(this.root,'当前可上阵 '+this.model.limit()+' 人',0,-98,24,c.ink);u.box(this.root,'guide',0,-377,644,140,c.panel);u.text(this.root,'三名同阶武将 → 原地或随机合成\n获胜选将，扩充阵容，继续征战',0,-369,27,c.paper,620,105);}
 /** 五个主入口都有明确本地用途，不让按钮进入未录制服务端页面。 */
 renderTabs(){const tabs=[['heroes','武将'],['camp','军营'],['home','征战'],['training','演武'],['rules','军略']];tabs.forEach(([page,name],i)=>this.ui.button(this.root,name,(i-2)*140,-584,130,()=>{this.page=page;this.render();},this.page===page?this.config.colors.red:this.config.colors.panel,82));}
 /** 武将图鉴显示真实模型、基础属性和本地技能规则。 */
 renderHeroes(){const u=this.ui,c=this.config.colors;u.text(this.root,'蜀汉群英 · 武将图鉴',0,451,32,c.gold);this.roster.forEach((h,i)=>{const y=339-i*170,n=u.box(this.root,h.name,0,y,658,154,c.panel);u.image(n,h.id+'-avatar.png',-244,0,128,128);u.text(n,h.name+' · '+h.role,-15,38,30,c.gold,310);u.text(n,'生命 '+h.hp+'    攻击 '+h.attack+'    射程 '+h.range,56,-10,23,c.paper,430);u.button(n,'详情',234,41,108,()=>this.details(h.id));u.text(n,h.skillName,60,-53,22,c.muted,410);});}
 /** 军营提供可重复招募与刷新，使用与战斗界面同一份经济。 */
 renderCamp(){const u=this.ui,c=this.config.colors;u.text(this.root,'军营招募',0,443,36,c.gold);u.text(this.root,'军资 '+this.model.state.gold+'  ·  武将 '+this.model.state.units.length+'/'+this.config.capacity,0,387,25);this.model.state.shop.forEach((id,i)=>{const x=(i-1)*224,h=this.roster.find(r=>r.id===id),n=u.box(this.root,'recruit-'+i,x,142,211,370,c.panel);if(h){u.actor(n,{uid:100+i,heroId:id,star:1},0,0,1,false);u.text(n,h.name,0,142,30,c.gold,200);u.text(n,h.role,0,-103,23,c.muted,200);u.button(n,this.config.recruitCost+' 军资',0,-150,180,()=>this.act(()=>{this.selected=this.model.recruit(i);this.message='招募成功，已加入备战席';}));}else u.text(n,'已招募',0,0,28,c.muted,200);});u.button(this.root,'刷新招募 · '+this.config.refreshCost+' 军资',0,-112,455,()=>this.act(()=>{this.model.refresh();this.message='招募列表已更新';}));u.text(this.root,this.message,0,-201,23,c.gold,650,75);u.text(this.root,'战胜敌军可免费三选一招募武将\n相同武将保留为独立棋子，合成由你决定',0,-330,26,c.paper,650,110);u.button(this.root,'返回布阵',0,-453,350,()=>{this.page='battle';this.render();});}
 /** 演武使用当前阵容和同一战斗算法，但不产生军资与关卡奖励。 */
 renderTraining(){const u=this.ui,c=this.config.colors;u.text(this.root,'演武场',0,399,45,c.gold);u.actor(this.root,{uid:0,heroId:this.config.trainingHero,star:1},0,83,2,false);u.text(this.root,'检验站位与武将搭配\n演武不推进关卡，不消耗军资',0,-141,28,c.paper,620,120);u.button(this.root,'以当前阵容演武',0,-309,470,()=>this.act(()=>this.start(true)));u.button(this.root,'先去调整阵容',0,-414,470,()=>{this.page='battle';this.render();},c.panel);u.text(this.root,this.message,0,-490,22,c.gold);}
 /** 用玩家可理解的规则说明站位、合成、羁绊与存档。 */
 renderRules(){const u=this.ui,c=this.config.colors;u.text(this.root,'军略 · 用兵之道',0,422,36,c.gold);const lines=[['布阵','拖动武将到己方三排；拖到已有武将处交换。\n也可先点武将，再点目标格子。'],['合成','三名相同、同阶武将可合成为一名高阶武将。\n原地升级保留身份；随机升级更换武将。'],['站位','近战自动接近敌人，远程在射程内攻击。\n单位不能穿过其他存活武将。'],['羁绊','同职业 '+this.config.synergyThreshold+' 名武将上阵，攻击提高 '+Math.round(this.config.synergyAttackBonus*100)+'%。\n最高 '+this.config.maxStar+' 阶；胜场提升上阵人数，最多 '+this.config.maxDeployedLimit+' 人。'],['存档','布阵、招募和战果自动保存。\n退出后待领取战果仍保留，不会重复发奖。']];lines.forEach(([title,text],i)=>{const y=284-i*173;u.box(this.root,title,0,y,654,155,c.panel);u.text(this.root,title,-245,y+40,27,c.gold,130);u.text(this.root,text,0,y-23,23,c.paper,620,85);});}
 /** 绘制原版视角的敌我棋盘、备战席和底部操作。 */
 renderBattle(){const u=this.ui,c=this.config.colors,s=this.model.state;u.image(this.root,this.config.battleImage,0,25,720,1090);u.box(this.root,'battle-header',0,568,714,130,c.panel);u.button(this.root,'返回',-286,584,120,()=>{if(this.playing)this.finish();this.page='home';this.render();},c.panel,60);u.text(this.root,this.chapter(),47,593,28,c.gold,465);u.text(this.root,'军资 '+s.gold+'  ·  上阵 '+s.units.filter(x=>x.slot>=0).length+'/'+this.model.limit(),32,539,24,c.paper,520);u.text(this.root,'敌军',-300,430,23,c.red,100);u.text(this.root,'己方',-300,107,23,c.ink,100);
  for(let y=0;y<this.config.rows;y++)for(let x=0;x<this.config.columns;x++){const p=this.position(x,y),slot=y*this.config.columns+x,n=u.box(this.root,'slot-'+slot,p.x,p.y,this.config.layout.boardX[y]-7,this.config.layout.boardHitHeight-8,'#A99B7080',false);n.on(this.cc.Node.EventType.TOUCH_END,()=>{if(this.selected)this.act(()=>{this.model.deploy(this.selected,slot);this.message='阵容已保存';});});}
  const final=s.pending?s.pending.battle.initial.map(a=>({...a,...s.pending.battle.final.find(f=>f.uid===a.uid)})):null;
  if(final){for(const unit of final){const p=this.position(unit.x,unit.y),actor=u.actor(this.root,unit,p.x,p.y,this.config.layout.modelScale);this.actors.set(unit.uid,actor);if(unit.hp===0){actor.alive=false;this.assets.skeleton(unit.heroId).then(()=>u.animate(actor,'dead'));}}}
  else{for(const unit of this.model.enemies()){const p=this.position(unit.slot%this.config.columns,Math.floor(unit.slot/this.config.columns)+this.config.rows);const a=u.actor(this.root,{...unit,side:'enemy'},p.x,p.y,this.config.layout.modelScale);this.actors.set(unit.uid,a);}for(const unit of s.units.filter(x=>x.slot>=0).sort((a,b)=>b.slot-a.slot)){const p=this.position(unit.slot%this.config.columns,Math.floor(unit.slot/this.config.columns));this.drawFriendly(unit,p.x,p.y,this.config.layout.modelScale);}}
  if(s.pending){this.reward();return;}
  u.box(this.root,'bench',0,-339,712,151,c.panel);const start=this.benchPage*this.config.layout.benchPageSize,bench=s.units.filter(x=>x.slot<0),shown=bench.slice(start,start+this.config.layout.benchPageSize);shown.forEach((unit,i)=>this.drawFriendly(unit,(i-2.5)*this.config.layout.benchSpacing,this.config.layout.benchY,this.config.layout.benchScale));u.text(this.root,'备战席 '+bench.length+' 人',0,-407,21,c.paper);if(bench.length>this.config.layout.benchPageSize)u.button(this.root,'换页',282,-400,125,()=>{this.benchPage=this.benchPage?0:1;this.render();},c.panel,46);
  const selected=s.units.find(x=>x.uid===this.selected),hero=selected&&this.roster.find(h=>h.id===selected.heroId);u.text(this.root,hero?'已选 '+hero.name+'  '+selected.star+' 阶  ·  拖动或点击格子布阵':this.message,0,-451,23,c.paper,692,55);
  u.button(this.root,'详情 / 合成',-227,-509,210,()=>{if(hero)this.details(hero.id,selected.uid);else{this.message='请先点击一名己方武将';this.render();}},c.panel);u.button(this.root,'选中下阵',0,-509,210,()=>this.act(()=>this.model.deploy(this.selected,-1)),c.panel);u.button(this.root,'军营招募',227,-509,210,()=>{this.page='camp';this.render();},c.panel);
  u.button(this.root,'开始战斗',140,-591,370,()=>this.act(()=>this.start(false)));u.button(this.root,'阵容说明',-237,-591,206,()=>{this.page='rules';this.render();},c.panel);
 }
 /** 角色触控支持点击选择、拖动交换和拖回备战席。 */
 drawFriendly(unit,x,y,scale){const u=this.ui,actor=u.actor(this.root,unit,x,y,scale);this.actors.set(unit.uid,actor);if(this.selected===unit.uid){const g=actor.node.addComponent(this.cc.Graphics);g.strokeColor=new this.cc.Color(this.config.colors.gold);g.lineWidth=3;g.ellipse(0,0,42,14);g.stroke();}let start=null,moved=false;
  actor.node.on(this.cc.Node.EventType.TOUCH_START,event=>{event.propagationStopped=true;start=event.getUILocation();moved=false;actor.node.setSiblingIndex(this.root.children.length-1);});
  actor.node.on(this.cc.Node.EventType.TOUCH_MOVE,event=>{event.propagationStopped=true;const p=event.getUILocation();if(start&&Math.hypot(p.x-start.x,p.y-start.y)>this.config.layout.dragThreshold)moved=true;if(moved){const q=this.root.getComponent(this.cc.UITransform).convertToNodeSpaceAR(new this.cc.Vec3(p.x,p.y,0));actor.node.setPosition(q.x,q.y);}});
  actor.node.on(this.cc.Node.EventType.TOUCH_END,event=>{event.propagationStopped=true;this.selected=unit.uid;if(moved){const p=event.getUILocation(),q=this.root.getComponent(this.cc.UITransform).convertToNodeSpaceAR(new this.cc.Vec3(p.x,p.y,0)),slot=this.slotAt(q);this.act(()=>{if(slot!==null)this.model.deploy(unit.uid,slot);else if(q.y< -260&&q.y> -425)this.model.deploy(unit.uid,-1);else throw Error('请放在己方棋盘或备战席');this.message='阵容已保存';});}else this.render();});
  actor.node.on(this.cc.Node.EventType.TOUCH_CANCEL,()=>this.render());return actor;
 }
 /** 模态层拦截下层输入，所有关闭入口都只影响当前视图。 */
 overlay(){if(this.modal?.isValid)this.modal.destroy();const m=this.ui.box(this.root,'modal',0,0,720,1280,'#15120FDD',false);m.addComponent(this.cc.BlockInputEvents);this.modal=m;return m;}
 /** 详情展示当前阶级属性，并显式选择原地或随机合成。 */
 details(id,uid=null){const hero=this.roster.find(h=>h.id===id),unit=uid?this.model.unit(uid):null,star=unit?.star||1,u=this.ui,c=this.config.colors,m=this.overlay();u.box(m,'details',0,0,638,1100,c.panel);u.text(m,hero.name+' · '+star+' 阶',0,473,39,c.gold);u.actor(m,{uid:0,heroId:id,star},0,193,1.7,false);u.text(m,hero.role+'    射程 '+hero.range,0,139,28);u.text(m,'生命 '+Math.round(hero.hp*Math.pow(this.config.hpGrowth,star-1))+'    攻击 '+Math.round(hero.attack*Math.pow(this.config.attackGrowth,star-1))+'\n护甲 '+hero.armor+'    攻击间隔 '+hero.interval+' 秒',0,55,27,c.paper,600,100);u.text(m,hero.skillName,0,-67,32,c.gold);u.text(m,hero.description,0,-151,26,c.paper,570,126);
  if(unit){const count=this.model.state.units.filter(x=>x.heroId===id&&x.star===star).length;u.text(m,'同阶武将 '+count+'/'+this.config.mergeCount+' · '+(star>=this.config.maxStar?'已达最高阶':'三合一升阶'),0,-253,25,c.gold);u.button(m,'原地合成',-148,-330,268,()=>this.act(()=>{this.model.merge(uid,'same');this.message='原地合成成功';}));u.button(m,'随机合成',148,-330,268,()=>this.act(()=>{this.model.merge(uid,'random');this.message='随机合成成功';}));u.button(m,'遣返武将',0,-422,330,()=>this.act(()=>{this.model.sell(uid);this.selected=null;this.message='武将已遣返，返还部分军资';}),c.panel);}
  u.button(m,'关闭',0,-504,300,()=>{m.destroy();this.modal=null;},c.panel);
 }
 /** 战报在开始时已经落盘，计时器只推进展示，不决定奖励。 */
 start(training){const battle=this.model.fight(training);this.page='battle';this.render();if(this.modal){this.modal.destroy();this.modal=null;}for(const a of this.actors.values()){a.node.destroy();}this.actors.clear();for(const unit of battle.initial){const p=this.position(unit.x,unit.y);this.actors.set(unit.uid,this.ui.actor(this.root,unit,p.x,p.y,this.config.layout.modelScale));}this.playing=true;this.replay=battle;this.elapsed=0;this.eventIndex=0;this.lastTime=Date.now();this.ui.box(this.root,'play-controls',0,-491,715,277,this.config.colors.panel);this.status=this.ui.text(this.root,'两军交战',0,-431,29,this.config.colors.gold);this.speedButton=this.ui.button(this.root,'速度 ×'+this.speed,-178,-565,295,()=>{const list=this.config.speedOptions;this.speed=list[(list.indexOf(this.speed)+1)%list.length];this.speedButton.getComponentInChildren(this.cc.Label).string='速度 ×'+this.speed;},this.config.colors.panel);this.ui.button(this.root,'跳过动画',178,-565,295,()=>this.finish());this.timer=setInterval(()=>this.tick(),40);}
 /** 按事件时间播放，倍速只改变展示速度，不改变模拟或存档。 */
 tick(){const now=Date.now();this.elapsed+=(now-this.lastTime)/1000*this.speed;this.lastTime=now;while(this.eventIndex<this.replay.events.length&&this.replay.events[this.eventIndex].t<=this.elapsed)this.apply(this.replay.events[this.eventIndex++]);if(this.elapsed>this.replay.duration+1)this.finish();}
 /** 应用移动、出手、命中与死亡事件，不重建整个场景。 */
 apply(event){const cc=this.cc,u=this.ui,actor=this.actors.get(event.uid),target=this.actors.get(event.target);if(event.type==='move'&&actor){const p=this.position(event.x,event.y);u.animate(actor,'run',true);cc.tween(actor.node).to(event.duration/this.speed,{position:new cc.Vec3(p.x,p.y,0)}).call(()=>u.animate(actor,'idle',true)).start();}
  if(event.type==='attack'&&actor){u.animate(actor,event.skill?'skill2':'skill1');if(this.status)this.status.string=event.skill?event.skillName:'两军交战';if(target&&event.ranged)this.projectile(actor,target,event.skill);}
  if(event.type==='damage'&&target){u.health(target,event.hp);this.damageText(target,event.damage,event.critical,event.skill);if(event.hp>0&&!event.skill){target.body.setScale(this.config.layout.modelScale*1.06,this.config.layout.modelScale*1.06,1);cc.tween(target.body).to(.12,{scale:new cc.Vec3(this.config.layout.modelScale,this.config.layout.modelScale,1)}).start();}}
  if(event.type==='death'&&actor){actor.alive=false;cc.Tween.stopAllByTarget(actor.node);u.animate(actor,'dead');}
 }
 /** 远程箭矢或法术光点沿真实目标位置移动，与命中前摇保持一致。 */
 projectile(actor,target,skill){const cc=this.cc,n=this.ui.node(this.root,'projectile',actor.node.position.x,actor.node.position.y+55),g=n.addComponent(cc.Graphics);g.fillColor=new cc.Color(skill?'#E5AF44':'#EEE3C0');g.circle(0,0,skill?9:4);g.fill();cc.tween(n).to(this.config.attackDelay/this.speed,{position:new cc.Vec3(target.node.position.x,target.node.position.y+45,0)}).call(()=>n.destroy()).start();}
 /** 飘字和命中光圈独立于角色骨骼，不修改技能结算。 */
 damageText(actor,damage,critical,skill){const cc=this.cc,p=actor.node.position,n=this.ui.node(this.root,'hit',p.x,p.y+65);this.ui.text(n,'-'+damage,0,0,critical?31:25,skill?'#FFCF60':'#FFF3CE',120,40);if(skill){const g=n.addComponent(cc.Graphics);g.strokeColor=new cc.Color('#E8B652');g.lineWidth=4;g.circle(0,-30,35);g.stroke();}const opacity=n.addComponent(cc.UIOpacity);cc.tween(n).by(.65,{position:new cc.Vec3(0,50,0)}).call(()=>n.destroy()).start();cc.tween(opacity).to(.65,{opacity:0}).start();}
 /** 结束和跳过仅停止动画，领取使用同一个已保存的 pending。 */
 finish(){clearInterval(this.timer);this.timer=null;this.playing=false;this.render();}
 /** 通关选将与奖励一次领取，重启后可恢复同一待领取结果。 */
 reward(){const p=this.model.state.pending;if(!p)return;const u=this.ui,c=this.config.colors,m=this.overlay();u.box(m,'reward-panel',0,0,674,810,c.panel);u.text(m,p.training?'演武结束':p.battle.result==='win'?'凯旋 · 通关奖励':p.battle.result==='loss'?'战败 · 整军再战':'交战超时 · 平局',0,325,34,c.gold);u.text(m,'军资 +'+p.gold+'  ·  '+p.battle.duration.toFixed(1)+' 秒',0,260,26);p.choices.forEach((id,i)=>{const x=(i-1)*214,h=this.roster.find(r=>r.id===id),n=u.box(m,'reward-'+i,x,26,203,330,c.panel);u.text(n,h.name,0,124,29,c.gold,195);u.actor(n,{uid:100+i,heroId:id,star:1},0,-10,.9,false);u.button(n,'选择',0,-120,172,()=>this.act(()=>{this.model.claim(i);this.selected=null;this.message='战果已保存，继续调整阵容';}));});if(!p.choices.length)u.text(m,p.training?'本次演武不发放奖励、不推进关卡':'保留全部武将，调整站位后可以重试',0,37,27,c.paper,600,120);u.button(m,p.choices.length?'只领取军资':'继续',0,-260,430,()=>this.act(()=>{this.model.claim();this.selected=null;this.message='结算已保存';}));u.text(m,'战果已保存 · 只可领取一次',0,-345,22,c.muted);}
}
module.exports={PlayView};
