"use strict";
const c=require('./vip-config'),data=require('./vip-data'),service=require('./vip'),ui=require('./benefit-ui');
/** VIP入口与等级列表复用原版橙金宝石徽章，未解锁等级使用灰色纹理。 */
function badge(v,p,x,y,size,locked=false){const n=v.ui.node(p,'vip-badge',x,y,size,size),icon=v.ui.image(n,c.badge.icon,0,0,size,size);icon.getComponent(v.cc.Sprite).grayscale=locked;return n;}
/** 等级文字使用亮金粗体和深色描边，在彩色及灰色徽章下保持对比。 */
function rankLabel(v,parent,text){const l=c.badge.label,label=v.ui.text(parent,text,0,l.y,l.font,l.color,l.width,l.height);label.isBold=true;const outline=label.node.addComponent(v.cc.LabelOutline);outline.color=new v.cc.Color(l.outline);outline.width=l.outlineWidth;return label;}
/** VIP全部等级可滚动预览，礼包资格永远从实际积分推导。 */
function open(v,selected=service.level(v.model)){const m=v.model,s=service.state(m),level=service.level(m),row=data[selected],l=c.layout,p=ui.panel(v,'VIP礼包',l),u=v.ui;u.box(p,'vip-banner',0,l.bannerY,608,l.bannerHeight,'#753826');u.text(p,'超级VIP',55,377,48,'#FFE345',390,65);const daily=ui.button(v,p,'每日礼包',-220,302,142,()=>ui.claim(v,()=>service.claim(m,'daily'),()=>open(v,selected)),'gold');require('./notification-view').badge(v,daily,'vip-daily',64,25,()=>service.state(m).daily!==m.progression.day());u.text(p,'VIP'+level+'   '+(level===data.length-1?'已满级':(s.points-data[level].vip_exp)+'/'+(data[level+1].vip_exp-data[level].vip_exp)),15,317,29,'#FFFFFF',270,45);ui.button(v,p,c.acquire.label,222,312,142,()=>require('./vip-navigation').open(v));u.text(p,'每个完整视频 +1积分，每日最多'+c.dailyCap+'，今日剩余'+service.remaining(m),0,256,23,'#FFF0CC',594,43);const sc=ui.scroll(v,p,'vip-level-list',l.tabsX,l.tabsY,l.tabsWidth,l.tabsHeight,data.length*l.tabGap,v.vipOffset||0,n=>v.vipOffset=n);data.forEach((r,i)=>{const y=l.tabsHeight/2-l.tabGap/2-i*l.tabGap,n=badge(v,sc.content,0,y,72,i>level);rankLabel(v,n,'VIP'+i);if(i===selected){const g=n.addComponent(v.cc.Graphics);g.strokeColor=new v.cc.Color('#FFFF42');g.lineWidth=5;g.circle(0,0,39);g.stroke();}if(i<=level&&!s.gifts.includes(i))require('./notification-view').badge(v,n,'vip-level-'+i,34,28,()=>i<=service.level(m)&&!service.state(m).gifts.includes(i));n.on(v.cc.Node.EventType.TOUCH_END,e=>{e.propagationStopped=true;if(!sc.dragged)open(v,i);});});require('./vip-privileges-view').render(v,p,row,selected);u.text(p,'超值礼包',l.bodyX,-237,31,'#674322',l.bodyWidth,45);ui.items(v,p,row.gift,l.giftY,78,l.bodyX,false);if(selected>level)u.text(p,'达到VIP'+selected+'可领取',l.bodyX,l.buttonY,28,'#745B3D',l.bodyWidth,50);else if(s.gifts.includes(selected))u.text(p,'✓ 已领取',l.bodyX,l.buttonY,32,'#438B25',l.bodyWidth,50);else ui.button(v,p,'领取礼包',l.bodyX,l.buttonY,260,()=>ui.claim(v,()=>service.claim(m,'level',selected),()=>open(v,selected)));return p;}
/** 首页VIP入口位于战令上方，红点只代表可领取礼包。 */
function entry(v){const l=c.layout,n=badge(v,v.root,l.homeX,l.homeY,104);v.ui.text(n,'VIP',0,-47,29,'#FFFFFF',115,40);n.on(v.cc.Node.EventType.TOUCH_END,e=>{e.propagationStopped=true;open(v);});require('./notification-view').badge(v,n,'vip',44,40,()=>service.ready(v.model));return n;}
module.exports={open,entry,badge};
